module.exports = {
  apps: [
    {
      name: 'tibiahub-api',
      cwd: '/forge/tibiahub/backend',
      script: 'venv/bin/python',
      args: 'main.py',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        PYTHONUNBUFFERED: '1',
        APP_ENV: 'production',
        API_HOST: '127.0.0.1',
        API_PORT: '8001',
        TIBIAHUB_SECRETS_FILE: '/forge/tibiahub-secrets/runtime.env',
      },
      error_file: './logs/api-error.log',
      out_file: './logs/api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'tibiahub-frontend',
      cwd: '/forge/tibiahub/frontend',
      script: 'npx',
      args: 'vite preview --host 0.0.0.0 --port 5174',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'production',
        VITE_API_URL: '/api/v1',
      },
      error_file: './logs/frontend-error.log',
      out_file: './logs/frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'tibiahub-raffle-scheduler',
      cwd: '/forge/tibiahub/backend',
      script: 'venv/bin/python',
      args: '-m app.workers.raffle_scheduler',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        PYTHONUNBUFFERED: '1',
        APP_ENV: 'production',
        TIBIAHUB_SECRETS_FILE: '/forge/tibiahub-secrets/runtime.env',
      },
      error_file: './logs/raffle-scheduler-error.log',
      out_file: './logs/raffle-scheduler-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'tibiahub-knowledge-worker',
      cwd: '/forge/tibiahub/backend',
      script: 'venv/bin/python',
      args: '-m app.knowledge.workers.knowledge_worker',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      restart_delay: 5000,
      kill_timeout: 30000,
      stop_exit_codes: [0],
      watch: false,
      max_memory_restart: '350M',
      env: {
        PYTHONUNBUFFERED: '1',
        APP_ENV: 'production',
        KNOWLEDGE_WORKER_ENABLED: 'true',
        TIBIAHUB_SECRETS_FILE: '/forge/tibiahub-secrets/runtime.env',
      },
      error_file: './logs/knowledge-worker-error.log',
      out_file: './logs/knowledge-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'tibiahub-email-worker',
      cwd: '/forge/tibiahub/backend',
      script: 'venv/bin/python',
      args: '-m app.workers.email_worker',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      restart_delay: 5000,
      kill_timeout: 30000,
      stop_exit_codes: [0],
      watch: false,
      max_memory_restart: '250M',
      env: {
        PYTHONUNBUFFERED: '1',
        APP_ENV: 'production',
        EMAIL_WORKER_ENABLED: 'true',
        TIBIAHUB_SECRETS_FILE: '/forge/tibiahub-secrets/runtime.env',
      },
      error_file: './logs/email-worker-error.log',
      out_file: './logs/email-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'tibiahub-sync-worker',
      cwd: '/forge/tibiahub/backend',
      script: 'venv/bin/python',
      args: '-m app.workers.sync_worker',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      restart_delay: 5000,
      kill_timeout: 30000,
      stop_exit_codes: [0],
      watch: false,
      max_memory_restart: '450M',
      env: {
        PYTHONUNBUFFERED: '1',
        APP_ENV: 'production',
        SYNC_WORKER_ENABLED: 'true',
        TIBIAHUB_SECRETS_FILE: '/forge/tibiahub-secrets/runtime.env',
      },
      error_file: './logs/sync-worker-error.log',
      out_file: './logs/sync-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
  ],
};
