import { FormEvent, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { AlertCircle, ChevronRight, Plus, Users } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { useAuth } from '../../context/AuthContext';
import { EmptyState, MobileSectionTabs, WorkspaceHeader } from '../../components/workspace/WorkspacePrimitives';
import { LeadershipApplication, LeadershipOpening, LeadershipSummary, leadershipApi } from '../../services/leadership';

export default function LeadershipRecruitment({ guildKey, guildName }: { guildKey?: string; guildName?: string }) {
  const { t } = useTranslation(); const { user } = useAuth(); const [summary, setSummary] = useState<LeadershipSummary | null>(null); const [openings, setOpenings] = useState<LeadershipOpening[]>([]); const [applications, setApplications] = useState<LeadershipApplication[]>([]); const [error, setError] = useState(false); const [filter, setFilter] = useState('all'); const [showOpening, setShowOpening] = useState(false); const [applying, setApplying] = useState<LeadershipOpening | null>(null);
  const load = async () => { setError(false); try { const result = await leadershipApi.summary(guildKey); setSummary(result); setOpenings(await leadershipApi.openings(guildKey)); setApplications(result.capabilities.review ? await leadershipApi.applications(guildKey) : guildKey ? [] : await leadershipApi.mine()); } catch { setError(true); } };
  useEffect(() => { void load(); }, [guildKey]);
  const detailBase = guildKey ? `/admin/guilds/${guildKey}/leadership/recruitment/applications` : '/guild/leadership/recruitment/applications';
  const statuses = ['all','applied','under_review','more_information_requested','interview','voting','accepted','rejected'];
  if (error) return <EmptyState title={t('leadership.errors.load')} description={t('leadership.errors.retry')} action={<button onClick={() => void load()} className="min-h-11 rounded-lg border border-slate-700 px-4">{t('leadership.actions.retry')}</button>} />;
  return <div className="space-y-4"><WorkspaceHeader title={t('leadership.recruitment.title')} subtitle={guildName || summary?.guild_name} action={summary?.capabilities.manage ? <button onClick={() => setShowOpening(value => !value)} className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-amber-500 px-4 font-semibold text-slate-950"><Plus className="h-4 w-4" />{t('leadership.openings.create')}</button> : undefined} />
    {showOpening && <OpeningForm guildKey={guildKey} onDone={() => { setShowOpening(false); void load(); }} />}
    {summary?.capabilities.review ? <><MobileSectionTabs active={filter} onChange={setFilter} tabs={statuses.map(id => ({ id, label: t(`leadership.status.${id}`) }))} /><div className="grid gap-3">{applications.filter(item => filter === 'all' || item.status === filter).map(item => <Link key={item.id} to={`${detailBase}/${item.id}`} className="flex min-h-20 items-center justify-between gap-3 rounded-xl border border-slate-800 p-4"><div className="min-w-0"><h2 className="truncate font-semibold">{item.character_name}</h2><p className="text-sm text-slate-400">{t(`leadership.status.${item.status}`)} · {new Date(item.submitted_at).toLocaleDateString()}</p></div><ChevronRight className="h-5 w-5 shrink-0" /></Link>)}</div></> : <div className="grid gap-3">{openings.filter(item => item.status === 'open').map(item => <article key={item.id} className="rounded-2xl border border-slate-800 p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{item.title}</h2><p className="mt-1 text-sm text-slate-400">{item.description}</p></div><Users className="h-5 w-5 text-amber-400" /></div><div className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><strong>{t('leadership.openings.responsibilities')}</strong><p className="mt-1 whitespace-pre-line text-slate-400">{item.responsibilities}</p></div><div><strong>{t('leadership.openings.requirements')}</strong><p className="mt-1 whitespace-pre-line text-slate-400">{item.requirements}</p></div></div><button disabled={!user?.tibia_character_name} onClick={() => setApplying(item)} className="mt-4 min-h-11 w-full rounded-lg bg-amber-500 font-semibold text-slate-950 disabled:opacity-50">{t('leadership.applications.apply')}</button></article>)}{openings.filter(item => item.status === 'open').length === 0 && <EmptyState title={t('leadership.openings.empty')} description={t('leadership.openings.emptyHelp')} />}{applications.map(item => <Link key={item.id} to={`${detailBase}/${item.id}`} className="rounded-xl border border-sky-800 p-4"><span className="text-xs text-sky-300">{t('leadership.applications.yours')}</span><h2 className="mt-1 font-semibold">{item.character_name}</h2><p className="text-sm text-slate-400">{t(`leadership.status.${item.status}`)}</p></Link>)}</div>}
    {applying && <ApplicationForm opening={applying} character={user?.tibia_character_name || ''} onCancel={() => setApplying(null)} onDone={() => { setApplying(null); void load(); }} />}
  </div>;
}

function OpeningForm({ guildKey, onDone }: { guildKey?: string; onDone: () => void }) { const { t } = useTranslation(); const [busy,setBusy]=useState(false); const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault(); if(busy)return; setBusy(true); const form=new FormData(event.currentTarget); await leadershipApi.createOpening({title:form.get('title'),description:form.get('description'),responsibilities:form.get('responsibilities'),requirements:form.get('requirements'),openings_count:Number(form.get('count')),allow_viceleader_review:true,voting_enabled:false,votes_required:1,target_count:4},guildKey); onDone();}; return <form onSubmit={submit} className="grid gap-3 rounded-xl border border-amber-500/20 p-4"><h2 className="font-semibold">{t('leadership.openings.create')}</h2><input name="title" required minLength={3} placeholder={t('leadership.openings.titleField')} className="min-h-11 rounded-lg bg-slate-950 px-3" /><textarea name="description" placeholder={t('leadership.openings.description')} className="min-h-24 rounded-lg bg-slate-950 p-3" /><textarea name="responsibilities" required minLength={10} defaultValue={t('leadership.openings.defaultResponsibilities')} className="min-h-32 rounded-lg bg-slate-950 p-3" /><textarea name="requirements" required minLength={10} defaultValue={t('leadership.openings.defaultRequirements')} className="min-h-32 rounded-lg bg-slate-950 p-3" /><input name="count" type="number" min={1} max={20} defaultValue={1} className="min-h-11 rounded-lg bg-slate-950 px-3" /><button disabled={busy} className="min-h-11 rounded-lg bg-amber-500 font-semibold text-slate-950">{t('leadership.actions.save')}</button></form>; }

function ApplicationForm({opening,character,onCancel,onDone}:{opening:LeadershipOpening;character:string;onCancel:()=>void;onDone:()=>void}) { const {t}=useTranslation(); const [answers,setAnswers]=useState({why_apply:'',contribution:'',availability:'',leadership_experience:''}); const [conduct,setConduct]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); useEffect(()=>{const handler=(event:BeforeUnloadEvent)=>{if(Object.values(answers).some(Boolean)){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[answers]); const submit=async(event:FormEvent)=>{event.preventDefault();if(busy)return;setBusy(true);setError('');try{await leadershipApi.apply(opening.id,{character_name:character,...answers,conduct_agreed:conduct});onDone();}catch{setError(t('leadership.errors.submit'));setBusy(false);}}; return <div className="fixed inset-0 z-50 flex items-end bg-black/70 sm:items-center sm:justify-center"><form onSubmit={submit} className="max-h-[92vh] w-full overflow-y-auto rounded-t-2xl bg-slate-900 p-4 sm:max-w-2xl sm:rounded-2xl"><h2 className="text-lg font-semibold">{t('leadership.applications.formTitle')}</h2><div className="mt-3 rounded-lg bg-slate-950 p-3 text-sm"><strong>{character}</strong><p className="text-slate-400">{t('leadership.applications.profileNotice')}</p></div>{(['why_apply','contribution','availability','leadership_experience'] as const).map(key=><label key={key} className="mt-4 block text-sm">{t(`leadership.questions.${key}`)}<textarea value={answers[key]} onChange={event=>setAnswers(value=>({...value,[key]:event.target.value}))} minLength={key==='availability'||key==='leadership_experience'?5:20} maxLength={2000} required className="mt-1 min-h-28 w-full rounded-lg bg-slate-950 p-3" /><span className="text-xs text-slate-500">{answers[key].length}/2000</span></label>)}<label className="mt-4 flex items-start gap-3 rounded-lg border border-slate-700 p-3 text-sm"><input type="checkbox" checked={conduct} onChange={event=>setConduct(event.target.checked)} required className="mt-1" />{t('leadership.conduct.text')}</label>{error&&<p role="alert" className="mt-3 text-sm text-red-300"><AlertCircle className="mr-1 inline h-4 w-4" />{error}</p>}<div className="sticky bottom-0 mt-4 flex gap-2 bg-slate-900 py-2"><button type="button" onClick={onCancel} className="min-h-11 flex-1 rounded-lg border border-slate-700">{t('leadership.actions.cancel')}</button><button disabled={busy} className="min-h-11 flex-1 rounded-lg bg-amber-500 font-semibold text-slate-950">{busy?t('leadership.actions.submitting'):t('leadership.actions.submit')}</button></div></form></div>; }
