import { useState } from 'react';
import { Link2, Loader2, Search } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { AppButton, Badge, FormField, Input, Panel } from '../ui';
import { useToast } from '../../context/ToastContext';
import { AdminCharacterSearchResult, GuildMember, guildManagementApi } from '../../services/guildManagement';

export default function AdminIdentityLinker({ users, onLinked }: { users: GuildMember[]; onLinked: (userId: number) => void }) {
  const { t } = useTranslation(); const toast = useToast(); const [userId, setUserId] = useState<number>(users[0]?.id || 0); const [query, setQuery] = useState(''); const [results, setResults] = useState<AdminCharacterSearchResult[]>([]); const [selected, setSelected] = useState<AdminCharacterSearchResult>(); const [reason, setReason] = useState(''); const [primary, setPrimary] = useState(true); const [transfer, setTransfer] = useState(false); const [confirmation, setConfirmation] = useState(''); const [busy, setBusy] = useState(false);
  const target = users.find(row => row.id === userId); const expected = selected && target ? `${transfer ? 'TRANSFER' : 'LINK'} ${selected.character_name} TO ${target.username}` : '';
  const search = async () => { if (query.trim().length < 2) return; setBusy(true); try { setResults(await guildManagementApi.searchCharacters(query.trim())); } catch { toast.error(t('identity.admin.searchError')); } finally { setBusy(false); } };
  const link = async () => { if (!selected || !target) return; setBusy(true); try { await guildManagementApi.linkCharacter({ user_id: target.id, character_name: selected.character_name, set_primary: primary, allow_transfer: transfer, reason, confirmation }); toast.success(t('identity.admin.linked')); setSelected(undefined); setReason(''); setConfirmation(''); onLinked(target.id); } catch { toast.error(t('identity.admin.linkError')); } finally { setBusy(false); } };
  return <Panel className="space-y-4 p-4"><div><h2 className="flex items-center gap-2 font-semibold"><Link2 className="size-4 text-primary" />{t('identity.admin.title')}</h2><p className="text-sm text-content-muted">{t('identity.admin.help')}</p></div><div className="grid gap-3 md:grid-cols-2"><FormField label={t('identity.admin.user')}><select className="min-h-11 rounded-lg border border-line bg-surface px-3" value={userId} onChange={event => { setUserId(Number(event.target.value)); setConfirmation(''); }}>{users.map(row => <option key={row.id} value={row.id}>{row.display_name || row.username} (@{row.username})</option>)}</select></FormField><FormField label={t('identity.admin.character')}><div className="flex gap-2"><Input value={query} onChange={event => setQuery(event.target.value)} /><AppButton onClick={() => void search()} disabled={busy}><Search className="size-4" /></AppButton></div></FormField></div>
    {query.trim().length >= 2 && <div className="space-y-2"><div className="grid gap-2 sm:grid-cols-2">{results.map(row => <button type="button" key={`${row.character_name}-${row.world_name}`} onClick={() => { setSelected(row); setTransfer(Boolean(row.linked_user_id && row.linked_user_id !== userId)); setConfirmation(''); }} className={`rounded-lg border p-3 text-left ${selected?.character_name === row.character_name ? 'border-primary bg-primary-subtle' : 'border-line'}`}><strong>{row.character_name}</strong><p className="text-xs text-content-muted">{row.world_name || '—'} · {row.guild_name || '—'} · {row.guild_rank || '—'}</p>{row.linked_user_id && <Badge tone="warning">{t('identity.admin.owned', { id: row.linked_user_id })}</Badge>}</button>)}</div><button type="button" className="text-sm text-primary underline" onClick={() => { setSelected({ character_name: query.trim() }); setTransfer(false); setConfirmation(''); }}>{t('identity.admin.useExact')}</button></div>}
    {selected && <div className="space-y-3 rounded-lg border border-line p-4"><p><strong>{selected.character_name}</strong> · {selected.world_name || '—'} · {selected.guild_name || '—'} · {selected.guild_rank || '—'}</p><FormField label={t('identity.admin.reason')}><Input value={reason} minLength={10} maxLength={1000} onChange={event => setReason(event.target.value)} /></FormField><label className="flex items-center gap-2"><input type="checkbox" checked={primary} onChange={event => setPrimary(event.target.checked)} />{t('identity.admin.setPrimary')}</label>{selected.linked_user_id && selected.linked_user_id !== userId && <label className="flex items-center gap-2 text-warning"><input type="checkbox" checked={transfer} onChange={event => { setTransfer(event.target.checked); setConfirmation(''); }} />{t('identity.admin.transfer')}</label>}<p className="text-sm text-content-muted">{t('identity.admin.type')} <code>{expected}</code></p><Input value={confirmation} onChange={event => setConfirmation(event.target.value)} /><AppButton variant={transfer ? 'danger' : 'primary'} disabled={busy || reason.trim().length < 10 || confirmation !== expected} onClick={() => void link()}>{busy && <Loader2 className="size-4 animate-spin" />}{t('identity.admin.confirm')}</AppButton></div>}
  </Panel>;
}
