import { useEffect, useState } from 'react';
import { Mail, RefreshCw, Send } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { AppButton, Badge, FormField, Input, Panel } from '../ui';
import { useToast } from '../../context/ToastContext';
import { adminEmailApi, EmailDiagnostics } from '../../services/adminEmail';

export default function EmailDiagnosticsPanel() {
  const { t, i18n } = useTranslation(); const toast = useToast(); const [data, setData] = useState<EmailDiagnostics>(); const [email, setEmail] = useState(''); const [busy, setBusy] = useState(false);
  const load = async () => { setBusy(true); try { setData(await adminEmailApi.diagnostics()); } catch { toast.error(t('identity.emailAdmin.error')); } finally { setBusy(false); } };
  useEffect(() => { void load(); }, []);
  const send = async () => { setBusy(true); try { await adminEmailApi.test(email, i18n.language.startsWith('es') ? 'es' : 'en'); toast.success(t('identity.emailAdmin.queued')); setEmail(''); await load(); } catch { toast.error(t('identity.emailAdmin.error')); } finally { setBusy(false); } };
  return <Panel className="space-y-4 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 font-semibold"><Mail className="size-5 text-primary" />{t('identity.emailAdmin.title')}</h2><p className="text-sm text-content-muted">{t('identity.emailAdmin.help')}</p></div><AppButton size="sm" variant="secondary" disabled={busy} onClick={() => void load()}><RefreshCw className="size-4" />{t('common.refresh')}</AppButton></div>{data && <dl className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Value label={t('identity.emailAdmin.configured')} value={t(data.configured ? 'common.yes' : 'common.no')} /><Value label={t('identity.emailAdmin.server')} value={`${data.host || '—'}:${data.port} · ${data.mode}`} /><Value label={t('identity.emailAdmin.from')} value={data.from_address || '—'} /><Value label={t('identity.emailAdmin.queue')} value={data.queue_depth} /><Value label={t('identity.emailAdmin.lastSuccess')} value={data.last_successful_delivery_at ? new Date(data.last_successful_delivery_at).toLocaleString() : '—'} /><Value label={t('identity.emailAdmin.failure')} value={data.last_failure_category || '—'} /><div><dt className="text-xs text-content-muted">{t('identity.emailAdmin.worker')}</dt><dd><Badge tone={data.worker?.state === 'idle' || data.worker?.state === 'running' ? 'success' : 'warning'}>{data.worker?.state || t('common.unknown')}</Badge></dd></div></dl>}<div className="grid gap-2 sm:grid-cols-[minmax(0,1fr)_auto]"><FormField label={t('identity.emailAdmin.recipient')}><Input type="email" value={email} onChange={event => setEmail(event.target.value)} /></FormField><div className="flex items-end"><AppButton disabled={busy || !email.includes('@')} onClick={() => void send()}><Send className="size-4" />{t('identity.emailAdmin.test')}</AppButton></div></div></Panel>;
}
function Value({ label, value }: { label: string; value: string | number }) { return <div><dt className="text-xs text-content-muted">{label}</dt><dd className="break-words font-medium">{value}</dd></div>; }
