"""postgresql foundation baseline

Revision ID: postgres_foundation_20260722
Revises:
Create Date: 2026-07-22 08:58:30.703212
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'postgres_foundation_20260722'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # PostgreSQL contrib extensions are part of the supported baseline.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
    # PostGIS is optional in Stage 1. Install it when the package is present and
    # the migration role is permitted to do so, but do not block this baseline.
    op.execute(
        """
        DO $tibiahub$
        BEGIN
          IF EXISTS (SELECT 1 FROM pg_available_extensions WHERE name = 'postgis') THEN
            BEGIN
              CREATE EXTENSION IF NOT EXISTS postgis;
            EXCEPTION WHEN insufficient_privilege THEN
              RAISE NOTICE 'PostGIS is available but requires elevated installation privileges';
            END;
          END IF;
        END
        $tibiahub$;
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_syncs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_name', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('processed_items', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_syncs_api_name'), 'api_syncs', ['api_name'], unique=False)
    op.create_index(op.f('ix_api_syncs_id'), 'api_syncs', ['id'], unique=False)
    op.create_table('cached_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('resolved_url', sa.String(length=1024), nullable=True),
    sa.Column('local_path', sa.String(length=1024), nullable=True),
    sa.Column('resource_key', sa.String(length=128), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('etag_hash', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetch_attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cached_resources_entity_id'), 'cached_resources', ['entity_id'], unique=False)
    op.create_index(op.f('ix_cached_resources_entity_type'), 'cached_resources', ['entity_type'], unique=False)
    op.create_index(op.f('ix_cached_resources_id'), 'cached_resources', ['id'], unique=False)
    op.create_index(op.f('ix_cached_resources_resource_key'), 'cached_resources', ['resource_key'], unique=False)
    op.create_index(op.f('ix_cached_resources_resource_type'), 'cached_resources', ['resource_type'], unique=False)
    op.create_table('catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('level_min', sa.Integer(), nullable=True),
    sa.Column('level_max', sa.Integer(), nullable=True),
    sa.Column('vocation', sa.Text(), nullable=True),
    sa.Column('exp_per_hour', sa.Integer(), nullable=True),
    sa.Column('profit_per_hour', sa.Integer(), nullable=True),
    sa.Column('creatures', sa.Text(), nullable=True),
    sa.Column('quest_reward', sa.Text(), nullable=True),
    sa.Column('quest_requirements', sa.Text(), nullable=True),
    sa.Column('strategy', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_id'), 'catalog', ['id'], unique=False)
    op.create_table('elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_elements_id'), 'elements', ['id'], unique=False)
    op.create_table('entity_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_key', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('search_count', sa.Integer(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_key', name='uq_entity_metadata_type_key')
    )
    op.create_index(op.f('ix_entity_metadata_entity_id'), 'entity_metadata', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_metadata_entity_key'), 'entity_metadata', ['entity_key'], unique=False)
    op.create_index(op.f('ix_entity_metadata_entity_type'), 'entity_metadata', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entity_metadata_id'), 'entity_metadata', ['id'], unique=False)
    op.create_table('guild_member_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_name', sa.String(length=200), nullable=False),
    sa.Column('character_name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('vocation', sa.String(length=100), nullable=True),
    sa.Column('rank', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('last_login', sa.String(length=100), nullable=True),
    sa.Column('world', sa.String(length=100), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guild_member_snapshots_character_name'), 'guild_member_snapshots', ['character_name'], unique=False)
    op.create_index(op.f('ix_guild_member_snapshots_guild_name'), 'guild_member_snapshots', ['guild_name'], unique=False)
    op.create_index(op.f('ix_guild_member_snapshots_id'), 'guild_member_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_guild_member_snapshots_snapshot_at'), 'guild_member_snapshots', ['snapshot_at'], unique=False)
    op.create_table('hunt_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('level_min', sa.Integer(), nullable=False),
    sa.Column('level_max', sa.Integer(), nullable=False),
    sa.Column('vocation', sa.Text(), nullable=True),
    sa.Column('exp_per_hour', sa.Integer(), nullable=True),
    sa.Column('profit_per_hour', sa.Integer(), nullable=True),
    sa.Column('creatures', sa.Text(), nullable=False),
    sa.Column('strategy', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hunt_catalog_id'), 'hunt_catalog', ['id'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_key', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('resolved_url', sa.String(length=1024), nullable=True),
    sa.Column('local_path', sa.String(length=1024), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_asset_key'), 'media_assets', ['asset_key'], unique=True)
    op.create_index(op.f('ix_media_assets_id'), 'media_assets', ['id'], unique=False)
    op.create_table('quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('wiki_url', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pdf_page_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quests_id'), 'quests', ['id'], unique=False)
    op.create_index(op.f('ix_quests_name'), 'quests', ['name'], unique=True)
    op.create_table('raffle_scheduler_state',
    sa.Column('worker_id', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_poll_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_code', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_table('sync_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('requester', sa.String(length=255), nullable=True),
    sa.Column('job_limit', sa.Integer(), nullable=True),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('current_entity_type', sa.String(length=50), nullable=True),
    sa.Column('current_offset', sa.Integer(), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('last_successful_external_id', sa.String(length=255), nullable=True),
    sa.Column('checkpoint', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('external_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_jobs_current_entity_type'), 'sync_jobs', ['current_entity_type'], unique=False)
    op.create_index(op.f('ix_sync_jobs_id'), 'sync_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_sync_jobs_job_type'), 'sync_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_sync_jobs_requested_by_user_id'), 'sync_jobs', ['requested_by_user_id'], unique=False)
    op.create_index(op.f('ix_sync_jobs_status'), 'sync_jobs', ['status'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('tibiawiki_hunting_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('min_level_recommended', sa.Integer(), nullable=True),
    sa.Column('max_level_recommended', sa.Integer(), nullable=True),
    sa.Column('creatures', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('loot_expectation', sa.String(length=50), nullable=True),
    sa.Column('common_loot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('raw_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tibiawiki_hunting_places_id'), 'tibiawiki_hunting_places', ['id'], unique=False)
    op.create_index(op.f('ix_tibiawiki_hunting_places_name'), 'tibiawiki_hunting_places', ['name'], unique=True)
    op.create_table('tibiawiki_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('attack', sa.Integer(), nullable=True),
    sa.Column('defense', sa.Integer(), nullable=True),
    sa.Column('armor', sa.Integer(), nullable=True),
    sa.Column('level_required', sa.Integer(), nullable=True),
    sa.Column('vocation_required', sa.String(length=100), nullable=True),
    sa.Column('tradeable', sa.Boolean(), nullable=True),
    sa.Column('stackable', sa.Boolean(), nullable=True),
    sa.Column('raw_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_index(op.f('ix_tibiawiki_items_id'), 'tibiawiki_items', ['id'], unique=False)
    op.create_index(op.f('ix_tibiawiki_items_name'), 'tibiawiki_items', ['name'], unique=True)
    op.create_index(op.f('ix_tibiawiki_items_type'), 'tibiawiki_items', ['type'], unique=False)
    op.create_table('tibiawiki_quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('group_name', sa.String(length=255), nullable=True),
    sa.Column('parent_page', sa.String(length=255), nullable=True),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.Column('min_level', sa.Integer(), nullable=True),
    sa.Column('max_level', sa.Integer(), nullable=True),
    sa.Column('experience_reward', sa.Integer(), nullable=True),
    sa.Column('treasure', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('npc', sa.String(length=255), nullable=True),
    sa.Column('rewards', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('requirements', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('related_creatures', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tibiawiki_quests_id'), 'tibiawiki_quests', ['id'], unique=False)
    op.create_index(op.f('ix_tibiawiki_quests_name'), 'tibiawiki_quests', ['name'], unique=True)
    op.create_index(op.f('ix_tibiawiki_quests_slug'), 'tibiawiki_quests', ['slug'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('guild_rank', sa.String(length=50), nullable=True),
    sa.Column('discord_id', sa.String(length=100), nullable=True),
    sa.Column('discord_username', sa.String(length=100), nullable=True),
    sa.Column('join_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('is_moderator', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('is_writer', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('vocation', sa.String(length=50), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('tibia_character_name', sa.String(length=100), nullable=True),
    sa.Column('world_name', sa.String(length=100), nullable=True),
    sa.Column('guild_name', sa.String(length=200), nullable=True),
    sa.Column('residence', sa.String(length=100), nullable=True),
    sa.Column('achievement_points', sa.Integer(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_app_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tibia_status', sa.String(length=50), nullable=True),
    sa.Column('tibia_last_error', sa.String(length=255), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_tibia_character_name'), 'users', ['tibia_character_name'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('guild_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('type', sa.Enum('GENERAL', 'CONTEST', 'HUNT', name='announcementtype'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('delete_reason', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_guild_name'), 'announcements', ['guild_name'], unique=False)
    op.create_index(op.f('ix_announcements_id'), 'announcements', ['id'], unique=False)
    op.create_table('creatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('normalized_name', sa.String(length=150), nullable=True),
    sa.Column('slug', sa.String(length=150), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('source_name', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=255), nullable=True),
    sa.Column('article', sa.String(length=10), nullable=True),
    sa.Column('plural', sa.String(length=100), nullable=True),
    sa.Column('hitpoints', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('armor', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('max_damage', sa.Integer(), nullable=True),
    sa.Column('summon_cost', sa.Integer(), nullable=True),
    sa.Column('convince_cost', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('occurrence', sa.String(length=20), nullable=True),
    sa.Column('is_boss', sa.Boolean(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('loot_value', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('behavior', sa.Text(), nullable=True),
    sa.Column('bestiary_class', sa.String(length=100), nullable=True),
    sa.Column('bestiary_level', sa.String(length=50), nullable=True),
    sa.Column('charm_points', sa.Integer(), nullable=True),
    sa.Column('classification', sa.String(length=50), nullable=True),
    sa.Column('creature_class', sa.String(length=100), nullable=True),
    sa.Column('primary_type', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('image_alias', sa.String(length=255), nullable=True),
    sa.Column('image_url_override', sa.String(length=1024), nullable=True),
    sa.Column('image_source_name', sa.String(length=255), nullable=True),
    sa.Column('image_locked', sa.Boolean(), nullable=True),
    sa.Column('image_asset_id', sa.Integer(), nullable=True),
    sa.Column('data_sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('missing_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('related_tasks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('locations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('raw_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['image_asset_id'], ['media_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creatures_classification'), 'creatures', ['classification'], unique=False)
    op.create_index(op.f('ix_creatures_external_id'), 'creatures', ['external_id'], unique=False)
    op.create_index(op.f('ix_creatures_id'), 'creatures', ['id'], unique=False)
    op.create_index(op.f('ix_creatures_name'), 'creatures', ['name'], unique=False)
    op.create_index(op.f('ix_creatures_normalized_name'), 'creatures', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_creatures_slug'), 'creatures', ['slug'], unique=False)
    op.create_index(op.f('ix_creatures_source_name'), 'creatures', ['source_name'], unique=False)
    op.create_table('guild_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type', sa.Enum('QUEST', 'HUNT', 'PVP', 'MEETING', 'OTHER', name='eventtype'), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('guild_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('delete_reason', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guild_events_guild_name'), 'guild_events', ['guild_name'], unique=False)
    op.create_index(op.f('ix_guild_events_id'), 'guild_events', ['id'], unique=False)
    op.create_table('guild_leadership_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_name', sa.String(length=200), nullable=False),
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('display_name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('recruitment_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_name', 'role_code', name='uq_leadership_role_guild_code')
    )
    op.create_index(op.f('ix_guild_leadership_roles_guild_name'), 'guild_leadership_roles', ['guild_name'], unique=False)
    op.create_table('hunt_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=True),
    sa.Column('normalized_name', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('source_provider', sa.String(length=50), nullable=True),
    sa.Column('source_name', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=255), nullable=True),
    sa.Column('min_level', sa.Integer(), nullable=False),
    sa.Column('max_level', sa.Integer(), nullable=True),
    sa.Column('recommended_level', sa.Integer(), nullable=True),
    sa.Column('recommended_vocations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('recommended_party_size', sa.String(length=50), nullable=True),
    sa.Column('exp_rating', sa.String(length=20), nullable=True),
    sa.Column('profit_rating', sa.String(length=20), nullable=True),
    sa.Column('danger_rating', sa.String(length=20), nullable=True),
    sa.Column('knights_recommended', sa.Boolean(), nullable=True),
    sa.Column('paladins_recommended', sa.Boolean(), nullable=True),
    sa.Column('sorcerers_recommended', sa.Boolean(), nullable=True),
    sa.Column('druids_recommended', sa.Boolean(), nullable=True),
    sa.Column('monks_recommended', sa.Boolean(), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('avg_exp_hour', sa.Integer(), nullable=True),
    sa.Column('avg_profit_hour', sa.Integer(), nullable=True),
    sa.Column('requires_quest', sa.Boolean(), nullable=True),
    sa.Column('quest_id', sa.Integer(), nullable=True),
    sa.Column('requires_premium', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tips', sa.Text(), nullable=True),
    sa.Column('location_x', sa.Integer(), nullable=True),
    sa.Column('location_y', sa.Integer(), nullable=True),
    sa.Column('location_z', sa.Integer(), nullable=True),
    sa.Column('map_x', sa.Integer(), nullable=True),
    sa.Column('map_y', sa.Integer(), nullable=True),
    sa.Column('map_z', sa.Integer(), nullable=True),
    sa.Column('map_bounds', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('map_image_url', sa.String(length=255), nullable=True),
    sa.Column('map_asset_id', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['map_asset_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hunt_zones_id'), 'hunt_zones', ['id'], unique=False)
    op.create_index(op.f('ix_hunt_zones_name'), 'hunt_zones', ['name'], unique=True)
    op.create_index(op.f('ix_hunt_zones_normalized_name'), 'hunt_zones', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_hunt_zones_slug'), 'hunt_zones', ['slug'], unique=False)
    op.create_index(op.f('ix_hunt_zones_source_name'), 'hunt_zones', ['source_name'], unique=False)
    op.create_index(op.f('ix_hunt_zones_source_provider'), 'hunt_zones', ['source_provider'], unique=False)
    op.create_table('raffles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('public_code', sa.String(length=6), nullable=False),
    sa.Column('guild_name', sa.String(length=200), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('world_name', sa.String(length=100), nullable=True),
    sa.Column('access_mode', sa.String(length=20), nullable=False),
    sa.Column('show_participants', sa.Boolean(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('registration_enabled', sa.Boolean(), nullable=False),
    sa.Column('run_mode', sa.String(length=20), nullable=False),
    sa.Column('scheduled_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('timezone_name', sa.String(length=64), nullable=False),
    sa.Column('eligibility_days', sa.Integer(), nullable=False),
    sa.Column('eligibility_cutoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('publication_status', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by_id', sa.Integer(), nullable=True),
    sa.Column('execution_state', sa.String(length=20), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_trigger', sa.String(length=20), nullable=True),
    sa.Column('scheduler_job_id', sa.String(length=255), nullable=True),
    sa.Column('claim_token', sa.String(length=64), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('last_error_summary', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('archive_after_days', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('last_executed_by_id', sa.Integer(), nullable=True),
    sa.Column('current_run_number', sa.Integer(), nullable=False),
    sa.Column('rerun_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('delete_reason', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_executed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['published_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raffles_id'), 'raffles', ['id'], unique=False)
    op.create_index(op.f('ix_raffles_public_code'), 'raffles', ['public_code'], unique=True)
    op.create_index('ix_raffles_scheduler_due', 'raffles', ['scheduled_run_at', 'next_retry_at'], unique=False, postgresql_where=sa.text("run_mode = 'automatic' AND is_deleted IS FALSE AND execution_state IN ('pending','failed','claimed','running')"))
    op.create_table('recruitments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=True),
    sa.Column('recruit_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='recruitmentstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruitments_id'), 'recruitments', ['id'], unique=False)
    op.create_table('sync_job_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('entity_name', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['sync_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_job_errors_entity_type'), 'sync_job_errors', ['entity_type'], unique=False)
    op.create_index(op.f('ix_sync_job_errors_external_id'), 'sync_job_errors', ['external_id'], unique=False)
    op.create_index(op.f('ix_sync_job_errors_id'), 'sync_job_errors', ['id'], unique=False)
    op.create_index(op.f('ix_sync_job_errors_job_id'), 'sync_job_errors', ['job_id'], unique=False)
    op.create_table('user_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=120), nullable=True),
    sa.Column('query', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activities_activity_type'), 'user_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_user_activities_created_at'), 'user_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_activities_id'), 'user_activities', ['id'], unique=False)
    op.create_index(op.f('ix_user_activities_user_id'), 'user_activities', ['user_id'], unique=False)
    op.create_table('user_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('vocation', sa.String(length=50), nullable=True),
    sa.Column('world_name', sa.String(length=100), nullable=True),
    sa.Column('guild_name', sa.String(length=200), nullable=True),
    sa.Column('guild_rank', sa.String(length=100), nullable=True),
    sa.Column('residence', sa.String(length=100), nullable=True),
    sa.Column('achievement_points', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_characters_character_name'), 'user_characters', ['character_name'], unique=True)
    op.create_index(op.f('ix_user_characters_id'), 'user_characters', ['id'], unique=False)
    op.create_table('workspace_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('workspace_type', sa.String(length=40), nullable=False),
    sa.Column('guild_name', sa.String(length=200), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=True),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('assisted', sa.Boolean(), nullable=False),
    sa.Column('safe_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_audits_action'), 'workspace_audits', ['action'], unique=False)
    op.create_index(op.f('ix_workspace_audits_actor_id'), 'workspace_audits', ['actor_id'], unique=False)
    op.create_index(op.f('ix_workspace_audits_guild_name'), 'workspace_audits', ['guild_name'], unique=False)
    op.create_table('creature_resistances',
    sa.Column('creature_id', sa.Integer(), nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creature_id'], ['creatures.id'], ),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], ),
    sa.PrimaryKeyConstraint('creature_id', 'element_id')
    )
    op.create_table('creature_weaknesses',
    sa.Column('creature_id', sa.Integer(), nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creature_id'], ['creatures.id'], ),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], ),
    sa.PrimaryKeyConstraint('creature_id', 'element_id')
    )
    op.create_table('event_attendance',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'MAYBE', 'DECLINED', 'BENCH', name='attendancestatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['guild_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'user_id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('public_code', sa.String(length=6), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('reward', sa.String(length=500), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('draw_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_slots', sa.Integer(), nullable=True),
    sa.Column('entry_cost', sa.String(length=200), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('winner_number', sa.Integer(), nullable=True),
    sa.Column('is_drawn', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('registration_enabled', sa.Boolean(), nullable=True),
    sa.Column('archive_after_days', sa.Integer(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('participant_mode', sa.String(length=20), nullable=True),
    sa.Column('active_days_limit', sa.Integer(), nullable=True),
    sa.Column('guild_name', sa.String(length=200), nullable=True),
    sa.Column('guild_world', sa.String(length=100), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('delete_reason', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_public_code'), 'events', ['public_code'], unique=True)
    op.create_index(op.f('ix_events_uuid'), 'events', ['uuid'], unique=True)
    op.create_table('guild_leadership_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_name', sa.String(length=200), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=100), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=False),
    sa.Column('assignment_source', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('in_game_promotion_status', sa.String(length=20), nullable=False),
    sa.Column('in_game_promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('in_game_promoted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['in_game_promoted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['guild_leadership_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guild_leadership_assignments_guild_name'), 'guild_leadership_assignments', ['guild_name'], unique=False)
    op.create_index(op.f('ix_guild_leadership_assignments_role_id'), 'guild_leadership_assignments', ['role_id'], unique=False)
    op.create_index(op.f('ix_guild_leadership_assignments_user_id'), 'guild_leadership_assignments', ['user_id'], unique=False)
    op.create_index('uq_leadership_active_assignment', 'guild_leadership_assignments', ['guild_name', 'role_id', 'user_id'], unique=True, postgresql_where=sa.text('is_active IS TRUE'))
    op.create_table('guild_leadership_openings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_name', sa.String(length=200), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.Column('openings_count', sa.Integer(), nullable=False),
    sa.Column('application_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('allow_viceleader_review', sa.Boolean(), nullable=False),
    sa.Column('voting_enabled', sa.Boolean(), nullable=False),
    sa.Column('votes_required', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['guild_leadership_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guild_leadership_openings_guild_name'), 'guild_leadership_openings', ['guild_name'], unique=False)
    op.create_index(op.f('ix_guild_leadership_openings_role_id'), 'guild_leadership_openings', ['role_id'], unique=False)
    op.create_index(op.f('ix_guild_leadership_openings_status'), 'guild_leadership_openings', ['status'], unique=False)
    op.create_table('internal_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('guild_name', sa.String(length=200), nullable=True),
    sa.Column('raffle_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.String(length=80), nullable=False),
    sa.Column('title_key', sa.String(length=255), nullable=False),
    sa.Column('message_key', sa.String(length=255), nullable=False),
    sa.Column('interpolation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('deep_link', sa.String(length=500), nullable=True),
    sa.Column('deduplication_key', sa.String(length=255), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['raffle_id'], ['raffles.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipient_user_id', 'deduplication_key', name='uq_notification_recipient_dedupe')
    )
    op.create_index(op.f('ix_internal_notifications_guild_name'), 'internal_notifications', ['guild_name'], unique=False)
    op.create_index(op.f('ix_internal_notifications_is_read'), 'internal_notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_internal_notifications_notification_type'), 'internal_notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_internal_notifications_raffle_id'), 'internal_notifications', ['raffle_id'], unique=False)
    op.create_index(op.f('ix_internal_notifications_recipient_user_id'), 'internal_notifications', ['recipient_user_id'], unique=False)
    op.create_table('loot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creature_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('normalized_name', sa.String(length=150), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('rarity', sa.String(length=20), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('min_amount', sa.Integer(), nullable=True),
    sa.Column('max_amount', sa.Integer(), nullable=True),
    sa.Column('item_value', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=True),
    sa.Column('item_image_url', sa.String(length=255), nullable=True),
    sa.Column('item_image_alias', sa.String(length=255), nullable=True),
    sa.Column('item_image_url_override', sa.String(length=1024), nullable=True),
    sa.Column('item_image_locked', sa.Boolean(), nullable=True),
    sa.Column('image_asset_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=255), nullable=True),
    sa.Column('raw_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['creature_id'], ['creatures.id'], ),
    sa.ForeignKeyConstraint(['image_asset_id'], ['media_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loot_external_id'), 'loot', ['external_id'], unique=False)
    op.create_index(op.f('ix_loot_id'), 'loot', ['id'], unique=False)
    op.create_index(op.f('ix_loot_normalized_name'), 'loot', ['normalized_name'], unique=False)
    op.create_table('raffle_eligibility_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raffle_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_number', sa.Integer(), nullable=False),
    sa.Column('cutoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone_name', sa.String(length=64), nullable=False),
    sa.Column('eligibility_days', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('eligible_count', sa.Integer(), nullable=False),
    sa.Column('excluded_count', sa.Integer(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['raffle_id'], ['raffles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raffle_id', 'snapshot_number', name='uq_raffle_snapshot_number')
    )
    op.create_index(op.f('ix_raffle_eligibility_snapshots_raffle_id'), 'raffle_eligibility_snapshots', ['raffle_id'], unique=False)
    op.create_table('raffle_manager_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raffle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('granted_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['raffle_id'], ['raffles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raffle_id', 'user_id', name='uq_raffle_manager_grant')
    )
    op.create_index(op.f('ix_raffle_manager_grants_raffle_id'), 'raffle_manager_grants', ['raffle_id'], unique=False)
    op.create_index(op.f('ix_raffle_manager_grants_user_id'), 'raffle_manager_grants', ['user_id'], unique=False)
    op.create_table('raffle_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raffle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=100), nullable=False),
    sa.Column('guild_rank', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('weight_multiplier', sa.Float(), nullable=False),
    sa.Column('is_eligible', sa.Boolean(), nullable=False),
    sa.Column('eligibility_override', sa.Boolean(), nullable=True),
    sa.Column('eligibility_override_reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('delete_reason', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['raffle_id'], ['raffles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raffle_id', 'character_name', name='uq_raffle_participant_character'),
    sa.UniqueConstraint('raffle_id', 'user_id', name='uq_raffle_participant_user')
    )
    op.create_index(op.f('ix_raffle_participants_character_name'), 'raffle_participants', ['character_name'], unique=False)
    op.create_index(op.f('ix_raffle_participants_id'), 'raffle_participants', ['id'], unique=False)
    op.create_index(op.f('ix_raffle_participants_raffle_id'), 'raffle_participants', ['raffle_id'], unique=False)
    op.create_index(op.f('ix_raffle_participants_user_id'), 'raffle_participants', ['user_id'], unique=False)
    op.create_table('raffle_prizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raffle_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('reward', sa.String(length=200), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['raffle_id'], ['raffles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raffle_prizes_id'), 'raffle_prizes', ['id'], unique=False)
    op.create_index(op.f('ix_raffle_prizes_raffle_id'), 'raffle_prizes', ['raffle_id'], unique=False)
    op.create_table('raffle_scheduler_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raffle_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=255), nullable=False),
    sa.Column('worker_id', sa.String(length=255), nullable=False),
    sa.Column('trigger', sa.String(length=30), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('failure_code', sa.String(length=100), nullable=True),
    sa.Column('failure_summary', sa.Text(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['raffle_id'], ['raffles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', name='uq_raffle_scheduler_job_id')
    )
    op.create_index(op.f('ix_raffle_scheduler_attempts_raffle_id'), 'raffle_scheduler_attempts', ['raffle_id'], unique=False)
    op.create_table('raffle_test_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raffle_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['raffle_id'], ['raffles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raffle_test_audits_action'), 'raffle_test_audits', ['action'], unique=False)
    op.create_index(op.f('ix_raffle_test_audits_raffle_id'), 'raffle_test_audits', ['raffle_id'], unique=False)
    op.create_table('spawn_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creature_id', sa.Integer(), nullable=False),
    sa.Column('hunt_zone_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['creature_id'], ['creatures.id'], ),
    sa.ForeignKeyConstraint(['hunt_zone_id'], ['hunt_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spawn_locations_id'), 'spawn_locations', ['id'], unique=False)
    op.create_table('event_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_number', sa.Integer(), nullable=True),
    sa.Column('entry_data', sa.Text(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_participant_user')
    )
    op.create_index(op.f('ix_event_participants_id'), 'event_participants', ['id'], unique=False)
    op.create_table('guild_leadership_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opening_id', sa.Integer(), nullable=False),
    sa.Column('applicant_user_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('why_apply', sa.Text(), nullable=False),
    sa.Column('contribution', sa.Text(), nullable=False),
    sa.Column('availability', sa.Text(), nullable=False),
    sa.Column('leadership_experience', sa.Text(), nullable=False),
    sa.Column('applicant_message', sa.Text(), nullable=True),
    sa.Column('profile_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('conduct_agreed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('conduct_version', sa.String(length=30), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_decision_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_decision_by_id', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('accepted_assignment_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accepted_assignment_id'], ['guild_leadership_assignments.id'], use_alter=True),
    sa.ForeignKeyConstraint(['applicant_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['final_decision_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opening_id'], ['guild_leadership_openings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guild_leadership_applications_applicant_user_id'), 'guild_leadership_applications', ['applicant_user_id'], unique=False)
    op.create_index(op.f('ix_guild_leadership_applications_opening_id'), 'guild_leadership_applications', ['opening_id'], unique=False)
    op.create_index(op.f('ix_guild_leadership_applications_status'), 'guild_leadership_applications', ['status'], unique=False)
    op.create_index('uq_leadership_active_application', 'guild_leadership_applications', ['opening_id', 'applicant_user_id'], unique=True, postgresql_where=sa.text("status IN ('applied','under_review','more_information_requested','interview','voting')"))
    op.create_foreign_key(
        'fk_leadership_application_assignment',
        'guild_leadership_applications',
        'guild_leadership_assignments',
        ['accepted_assignment_id'],
        ['id'],
    )
    op.create_table('public_event_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=100), nullable=False),
    sa.Column('character_level', sa.Integer(), nullable=True),
    sa.Column('character_vocation', sa.String(length=50), nullable=True),
    sa.Column('character_world', sa.String(length=100), nullable=True),
    sa.Column('last_login', sa.String(length=100), nullable=True),
    sa.Column('assigned_number', sa.Integer(), nullable=True),
    sa.Column('is_auto_loaded', sa.Boolean(), nullable=True),
    sa.Column('is_excluded', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('delete_reason', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'character_name', name='uq_public_event_participant_character')
    )
    op.create_index(op.f('ix_public_event_participants_id'), 'public_event_participants', ['id'], unique=False)
    op.create_table('raffle_eligibility_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=100), nullable=True),
    sa.Column('guild_name', sa.String(length=200), nullable=True),
    sa.Column('guild_rank', sa.String(length=100), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_eligible', sa.Boolean(), nullable=False),
    sa.Column('exclusion_code', sa.String(length=50), nullable=True),
    sa.Column('exclusion_summary', sa.String(length=255), nullable=True),
    sa.Column('source_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['raffle_eligibility_snapshots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'user_id', name='uq_raffle_snapshot_user')
    )
    op.create_index(op.f('ix_raffle_eligibility_entries_snapshot_id'), 'raffle_eligibility_entries', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_raffle_eligibility_entries_user_id'), 'raffle_eligibility_entries', ['user_id'], unique=False)
    op.create_table('raffle_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raffle_id', sa.Integer(), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('parent_run_id', sa.Integer(), nullable=True),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_code', sa.String(length=100), nullable=True),
    sa.Column('failure_summary', sa.Text(), nullable=True),
    sa.Column('algorithm_version', sa.String(length=50), nullable=False),
    sa.Column('entropy_commitment', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_run_id'], ['raffle_runs.id'], ),
    sa.ForeignKeyConstraint(['raffle_id'], ['raffles.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['raffle_eligibility_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raffle_id', 'run_number', name='uq_raffle_run_number')
    )
    op.create_index(op.f('ix_raffle_runs_raffle_id'), 'raffle_runs', ['raffle_id'], unique=False)
    op.create_table('raffle_winners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raffle_id', sa.Integer(), nullable=False),
    sa.Column('prize_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('executed_by_id', sa.Integer(), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('is_rerun', sa.Boolean(), nullable=False),
    sa.Column('rerun_reason', sa.Text(), nullable=True),
    sa.Column('participant_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['executed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['raffle_participants.id'], ),
    sa.ForeignKeyConstraint(['prize_id'], ['raffle_prizes.id'], ),
    sa.ForeignKeyConstraint(['raffle_id'], ['raffles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raffle_winners_id'), 'raffle_winners', ['id'], unique=False)
    op.create_index(op.f('ix_raffle_winners_participant_id'), 'raffle_winners', ['participant_id'], unique=False)
    op.create_index(op.f('ix_raffle_winners_prize_id'), 'raffle_winners', ['prize_id'], unique=False)
    op.create_index(op.f('ix_raffle_winners_raffle_id'), 'raffle_winners', ['raffle_id'], unique=False)
    op.create_table('guild_leadership_application_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=40), nullable=True),
    sa.Column('to_status', sa.String(length=40), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('actor_context', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('safe_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['guild_leadership_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guild_leadership_application_history_application_id'), 'guild_leadership_application_history', ['application_id'], unique=False)
    op.create_table('guild_leadership_application_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('audience', sa.String(length=20), nullable=False),
    sa.Column('message_type', sa.String(length=40), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['guild_leadership_applications.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guild_leadership_application_messages_application_id'), 'guild_leadership_application_messages', ['application_id'], unique=False)
    op.create_table('guild_leadership_interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('meeting_location', sa.String(length=255), nullable=False),
    sa.Column('interview_notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['guild_leadership_applications.id'], ),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_table('guild_leadership_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('voter_user_id', sa.Integer(), nullable=False),
    sa.Column('vote', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['guild_leadership_applications.id'], ),
    sa.ForeignKeyConstraint(['voter_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'voter_user_id', name='uq_leadership_vote_application_voter')
    )
    op.create_index(op.f('ix_guild_leadership_votes_application_id'), 'guild_leadership_votes', ['application_id'], unique=False)
    op.create_table('raffle_rerun_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raffle_id', sa.Integer(), nullable=False),
    sa.Column('source_run_id', sa.Integer(), nullable=False),
    sa.Column('new_run_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('positions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('override_delivered', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['new_run_id'], ['raffle_runs.id'], ),
    sa.ForeignKeyConstraint(['raffle_id'], ['raffles.id'], ),
    sa.ForeignKeyConstraint(['source_run_id'], ['raffle_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raffle_rerun_audits_raffle_id'), 'raffle_rerun_audits', ['raffle_id'], unique=False)
    op.create_table('raffle_run_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('prize_id', sa.Integer(), nullable=False),
    sa.Column('prize_position', sa.String(length=20), nullable=False),
    sa.Column('participant_user_id', sa.Integer(), nullable=False),
    sa.Column('participant_character_name', sa.String(length=100), nullable=False),
    sa.Column('selection_index', sa.Integer(), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('derived_entropy_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('superseded_by_result_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['participant_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prize_id'], ['raffle_prizes.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['raffle_runs.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_result_id'], ['raffle_run_results.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'prize_position', name='uq_raffle_run_position')
    )
    op.create_index(op.f('ix_raffle_run_results_is_active'), 'raffle_run_results', ['is_active'], unique=False)
    op.create_index(op.f('ix_raffle_run_results_run_id'), 'raffle_run_results', ['run_id'], unique=False)
    op.create_table('raffle_prize_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raffle_id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('delivery_deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_by_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delivered_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['raffle_id'], ['raffles.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['raffle_run_results.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('result_id', name='uq_raffle_delivery_result')
    )
    op.create_index(op.f('ix_raffle_prize_deliveries_raffle_id'), 'raffle_prize_deliveries', ['raffle_id'], unique=False)
    op.create_table('raffle_delivery_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.String(length=20), nullable=False),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('admin_override', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delivery_id'], ['raffle_prize_deliveries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raffle_delivery_audits_delivery_id'), 'raffle_delivery_audits', ['delivery_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raffle_delivery_audits_delivery_id'), table_name='raffle_delivery_audits')
    op.drop_table('raffle_delivery_audits')
    op.drop_index(op.f('ix_raffle_prize_deliveries_raffle_id'), table_name='raffle_prize_deliveries')
    op.drop_table('raffle_prize_deliveries')
    op.drop_index(op.f('ix_raffle_run_results_run_id'), table_name='raffle_run_results')
    op.drop_index(op.f('ix_raffle_run_results_is_active'), table_name='raffle_run_results')
    op.drop_table('raffle_run_results')
    op.drop_index(op.f('ix_raffle_rerun_audits_raffle_id'), table_name='raffle_rerun_audits')
    op.drop_table('raffle_rerun_audits')
    op.drop_index(op.f('ix_guild_leadership_votes_application_id'), table_name='guild_leadership_votes')
    op.drop_table('guild_leadership_votes')
    op.drop_table('guild_leadership_interviews')
    op.drop_index(op.f('ix_guild_leadership_application_messages_application_id'), table_name='guild_leadership_application_messages')
    op.drop_table('guild_leadership_application_messages')
    op.drop_index(op.f('ix_guild_leadership_application_history_application_id'), table_name='guild_leadership_application_history')
    op.drop_table('guild_leadership_application_history')
    op.drop_index(op.f('ix_raffle_winners_raffle_id'), table_name='raffle_winners')
    op.drop_index(op.f('ix_raffle_winners_prize_id'), table_name='raffle_winners')
    op.drop_index(op.f('ix_raffle_winners_participant_id'), table_name='raffle_winners')
    op.drop_index(op.f('ix_raffle_winners_id'), table_name='raffle_winners')
    op.drop_table('raffle_winners')
    op.drop_index(op.f('ix_raffle_runs_raffle_id'), table_name='raffle_runs')
    op.drop_table('raffle_runs')
    op.drop_index(op.f('ix_raffle_eligibility_entries_user_id'), table_name='raffle_eligibility_entries')
    op.drop_index(op.f('ix_raffle_eligibility_entries_snapshot_id'), table_name='raffle_eligibility_entries')
    op.drop_table('raffle_eligibility_entries')
    op.drop_index(op.f('ix_public_event_participants_id'), table_name='public_event_participants')
    op.drop_table('public_event_participants')
    op.drop_index('uq_leadership_active_application', table_name='guild_leadership_applications', postgresql_where=sa.text("status IN ('applied','under_review','more_information_requested','interview','voting')"))
    op.drop_index(op.f('ix_guild_leadership_applications_status'), table_name='guild_leadership_applications')
    op.drop_index(op.f('ix_guild_leadership_applications_opening_id'), table_name='guild_leadership_applications')
    op.drop_index(op.f('ix_guild_leadership_applications_applicant_user_id'), table_name='guild_leadership_applications')
    op.drop_table('guild_leadership_applications')
    op.drop_index(op.f('ix_event_participants_id'), table_name='event_participants')
    op.drop_table('event_participants')
    op.drop_index(op.f('ix_spawn_locations_id'), table_name='spawn_locations')
    op.drop_table('spawn_locations')
    op.drop_index(op.f('ix_raffle_test_audits_raffle_id'), table_name='raffle_test_audits')
    op.drop_index(op.f('ix_raffle_test_audits_action'), table_name='raffle_test_audits')
    op.drop_table('raffle_test_audits')
    op.drop_index(op.f('ix_raffle_scheduler_attempts_raffle_id'), table_name='raffle_scheduler_attempts')
    op.drop_table('raffle_scheduler_attempts')
    op.drop_index(op.f('ix_raffle_prizes_raffle_id'), table_name='raffle_prizes')
    op.drop_index(op.f('ix_raffle_prizes_id'), table_name='raffle_prizes')
    op.drop_table('raffle_prizes')
    op.drop_index(op.f('ix_raffle_participants_user_id'), table_name='raffle_participants')
    op.drop_index(op.f('ix_raffle_participants_raffle_id'), table_name='raffle_participants')
    op.drop_index(op.f('ix_raffle_participants_id'), table_name='raffle_participants')
    op.drop_index(op.f('ix_raffle_participants_character_name'), table_name='raffle_participants')
    op.drop_table('raffle_participants')
    op.drop_index(op.f('ix_raffle_manager_grants_user_id'), table_name='raffle_manager_grants')
    op.drop_index(op.f('ix_raffle_manager_grants_raffle_id'), table_name='raffle_manager_grants')
    op.drop_table('raffle_manager_grants')
    op.drop_index(op.f('ix_raffle_eligibility_snapshots_raffle_id'), table_name='raffle_eligibility_snapshots')
    op.drop_table('raffle_eligibility_snapshots')
    op.drop_index(op.f('ix_loot_normalized_name'), table_name='loot')
    op.drop_index(op.f('ix_loot_id'), table_name='loot')
    op.drop_index(op.f('ix_loot_external_id'), table_name='loot')
    op.drop_table('loot')
    op.drop_index(op.f('ix_internal_notifications_recipient_user_id'), table_name='internal_notifications')
    op.drop_index(op.f('ix_internal_notifications_raffle_id'), table_name='internal_notifications')
    op.drop_index(op.f('ix_internal_notifications_notification_type'), table_name='internal_notifications')
    op.drop_index(op.f('ix_internal_notifications_is_read'), table_name='internal_notifications')
    op.drop_index(op.f('ix_internal_notifications_guild_name'), table_name='internal_notifications')
    op.drop_table('internal_notifications')
    op.drop_index(op.f('ix_guild_leadership_openings_status'), table_name='guild_leadership_openings')
    op.drop_index(op.f('ix_guild_leadership_openings_role_id'), table_name='guild_leadership_openings')
    op.drop_index(op.f('ix_guild_leadership_openings_guild_name'), table_name='guild_leadership_openings')
    op.drop_table('guild_leadership_openings')
    op.drop_index('uq_leadership_active_assignment', table_name='guild_leadership_assignments', postgresql_where=sa.text('is_active IS TRUE'))
    op.drop_index(op.f('ix_guild_leadership_assignments_user_id'), table_name='guild_leadership_assignments')
    op.drop_index(op.f('ix_guild_leadership_assignments_role_id'), table_name='guild_leadership_assignments')
    op.drop_index(op.f('ix_guild_leadership_assignments_guild_name'), table_name='guild_leadership_assignments')
    op.drop_table('guild_leadership_assignments')
    op.drop_index(op.f('ix_events_uuid'), table_name='events')
    op.drop_index(op.f('ix_events_public_code'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_table('event_attendance')
    op.drop_table('creature_weaknesses')
    op.drop_table('creature_resistances')
    op.drop_index(op.f('ix_workspace_audits_guild_name'), table_name='workspace_audits')
    op.drop_index(op.f('ix_workspace_audits_actor_id'), table_name='workspace_audits')
    op.drop_index(op.f('ix_workspace_audits_action'), table_name='workspace_audits')
    op.drop_table('workspace_audits')
    op.drop_index(op.f('ix_user_characters_id'), table_name='user_characters')
    op.drop_index(op.f('ix_user_characters_character_name'), table_name='user_characters')
    op.drop_table('user_characters')
    op.drop_index(op.f('ix_user_activities_user_id'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_id'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_created_at'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_activity_type'), table_name='user_activities')
    op.drop_table('user_activities')
    op.drop_index(op.f('ix_sync_job_errors_job_id'), table_name='sync_job_errors')
    op.drop_index(op.f('ix_sync_job_errors_id'), table_name='sync_job_errors')
    op.drop_index(op.f('ix_sync_job_errors_external_id'), table_name='sync_job_errors')
    op.drop_index(op.f('ix_sync_job_errors_entity_type'), table_name='sync_job_errors')
    op.drop_table('sync_job_errors')
    op.drop_index(op.f('ix_recruitments_id'), table_name='recruitments')
    op.drop_table('recruitments')
    op.drop_index('ix_raffles_scheduler_due', table_name='raffles', postgresql_where=sa.text("run_mode = 'automatic' AND is_deleted IS FALSE AND execution_state IN ('pending','failed','claimed','running')"))
    op.drop_index(op.f('ix_raffles_public_code'), table_name='raffles')
    op.drop_index(op.f('ix_raffles_id'), table_name='raffles')
    op.drop_table('raffles')
    op.drop_index(op.f('ix_hunt_zones_source_provider'), table_name='hunt_zones')
    op.drop_index(op.f('ix_hunt_zones_source_name'), table_name='hunt_zones')
    op.drop_index(op.f('ix_hunt_zones_slug'), table_name='hunt_zones')
    op.drop_index(op.f('ix_hunt_zones_normalized_name'), table_name='hunt_zones')
    op.drop_index(op.f('ix_hunt_zones_name'), table_name='hunt_zones')
    op.drop_index(op.f('ix_hunt_zones_id'), table_name='hunt_zones')
    op.drop_table('hunt_zones')
    op.drop_index(op.f('ix_guild_leadership_roles_guild_name'), table_name='guild_leadership_roles')
    op.drop_table('guild_leadership_roles')
    op.drop_index(op.f('ix_guild_events_id'), table_name='guild_events')
    op.drop_index(op.f('ix_guild_events_guild_name'), table_name='guild_events')
    op.drop_table('guild_events')
    op.drop_index(op.f('ix_creatures_source_name'), table_name='creatures')
    op.drop_index(op.f('ix_creatures_slug'), table_name='creatures')
    op.drop_index(op.f('ix_creatures_normalized_name'), table_name='creatures')
    op.drop_index(op.f('ix_creatures_name'), table_name='creatures')
    op.drop_index(op.f('ix_creatures_id'), table_name='creatures')
    op.drop_index(op.f('ix_creatures_external_id'), table_name='creatures')
    op.drop_index(op.f('ix_creatures_classification'), table_name='creatures')
    op.drop_table('creatures')
    op.drop_index(op.f('ix_announcements_id'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_guild_name'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_tibia_character_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tibiawiki_quests_slug'), table_name='tibiawiki_quests')
    op.drop_index(op.f('ix_tibiawiki_quests_name'), table_name='tibiawiki_quests')
    op.drop_index(op.f('ix_tibiawiki_quests_id'), table_name='tibiawiki_quests')
    op.drop_table('tibiawiki_quests')
    op.drop_index(op.f('ix_tibiawiki_items_type'), table_name='tibiawiki_items')
    op.drop_index(op.f('ix_tibiawiki_items_name'), table_name='tibiawiki_items')
    op.drop_index(op.f('ix_tibiawiki_items_id'), table_name='tibiawiki_items')
    op.drop_table('tibiawiki_items')
    op.drop_index(op.f('ix_tibiawiki_hunting_places_name'), table_name='tibiawiki_hunting_places')
    op.drop_index(op.f('ix_tibiawiki_hunting_places_id'), table_name='tibiawiki_hunting_places')
    op.drop_table('tibiawiki_hunting_places')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_sync_jobs_status'), table_name='sync_jobs')
    op.drop_index(op.f('ix_sync_jobs_requested_by_user_id'), table_name='sync_jobs')
    op.drop_index(op.f('ix_sync_jobs_job_type'), table_name='sync_jobs')
    op.drop_index(op.f('ix_sync_jobs_id'), table_name='sync_jobs')
    op.drop_index(op.f('ix_sync_jobs_current_entity_type'), table_name='sync_jobs')
    op.drop_table('sync_jobs')
    op.drop_table('raffle_scheduler_state')
    op.drop_index(op.f('ix_quests_name'), table_name='quests')
    op.drop_index(op.f('ix_quests_id'), table_name='quests')
    op.drop_table('quests')
    op.drop_index(op.f('ix_media_assets_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_asset_key'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_hunt_catalog_id'), table_name='hunt_catalog')
    op.drop_table('hunt_catalog')
    op.drop_index(op.f('ix_guild_member_snapshots_snapshot_at'), table_name='guild_member_snapshots')
    op.drop_index(op.f('ix_guild_member_snapshots_id'), table_name='guild_member_snapshots')
    op.drop_index(op.f('ix_guild_member_snapshots_guild_name'), table_name='guild_member_snapshots')
    op.drop_index(op.f('ix_guild_member_snapshots_character_name'), table_name='guild_member_snapshots')
    op.drop_table('guild_member_snapshots')
    op.drop_index(op.f('ix_entity_metadata_id'), table_name='entity_metadata')
    op.drop_index(op.f('ix_entity_metadata_entity_type'), table_name='entity_metadata')
    op.drop_index(op.f('ix_entity_metadata_entity_key'), table_name='entity_metadata')
    op.drop_index(op.f('ix_entity_metadata_entity_id'), table_name='entity_metadata')
    op.drop_table('entity_metadata')
    op.drop_index(op.f('ix_elements_id'), table_name='elements')
    op.drop_table('elements')
    op.drop_index(op.f('ix_catalog_id'), table_name='catalog')
    op.drop_table('catalog')
    op.drop_index(op.f('ix_cached_resources_resource_type'), table_name='cached_resources')
    op.drop_index(op.f('ix_cached_resources_resource_key'), table_name='cached_resources')
    op.drop_index(op.f('ix_cached_resources_id'), table_name='cached_resources')
    op.drop_index(op.f('ix_cached_resources_entity_type'), table_name='cached_resources')
    op.drop_index(op.f('ix_cached_resources_entity_id'), table_name='cached_resources')
    op.drop_table('cached_resources')
    op.drop_index(op.f('ix_api_syncs_id'), table_name='api_syncs')
    op.drop_index(op.f('ix_api_syncs_api_name'), table_name='api_syncs')
    op.drop_table('api_syncs')
    # ### end Alembic commands ###
