import { lazy, Suspense, useCallback, useEffect, useRef, useState } from 'react';
import { Coins, Expand, Map, Minimize2, Plus, Shield, Sparkles, Swords, Trash2, User, Users, X, Zap, Scroll } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { huntZonesApi } from '../services/api';
import { tibiaMapApi, type HuntZoneMapContext, type TibiaMapBootstrap } from '../services/tibiaMap';
import AppButton from '../components/ui/AppButton'; import AppCard from '../components/ui/AppCard'; import AppInput from '../components/ui/AppInput'; import AppTabs from '../components/ui/AppTabs'; import PageHeader from '../components/ui/PageHeader'; import { Page } from '../components/ui';
import { faCompass } from '@fortawesome/free-solid-svg-icons';

const TibiaMap = lazy(() => import('../components/map/TibiaMapViewer'));
const VOCATIONS = [{ id: 'knight', icon: Shield }, { id: 'paladin', icon: Swords }, { id: 'sorcerer', icon: Zap }, { id: 'druid', icon: Sparkles }, { id: 'monk', icon: Scroll }];
const PAGE_SIZE = 6;
interface PartyMember { id: number; vocation: string; level: number }
interface CreaturePreview { id: number; name: string; slug?: string; image_url: string; hitpoints: number; experience: number; max_damage?: number; weaknesses: string[]; resistances: string[]; valuable_loot: Array<{ name: string; value: number; image_url?: string }> }
interface RecommendationItem { zone_id: number; zone_name: string; zone_slug?: string; score: number; min_level?: number; max_level?: number; suggested_level?: number; avg_exp_hour?: number; avg_profit_hour?: number; raw_creature_exp?: number; requires_premium?: boolean; requires_quest?: boolean; quest_name?: string; city?: string; region?: string; size?: string; location_z?: number; creatures?: CreaturePreview[] }
interface RecommendationResponse { recommendations: RecommendationItem[]; has_more: boolean; skip: number; limit: number; avg_level?: number; party_size?: number }

export default function HuntRecommendationsPage() {
  const { t } = useTranslation(); const [searchParams] = useSearchParams(); const preferredZone = searchParams.get('zone') || undefined;
  const [mode, setMode] = useState<'solo' | 'party'>('solo'); const [soloVocation, setSoloVocation] = useState('knight'); const [soloLevel, setSoloLevel] = useState(100);
  const [party, setParty] = useState<PartyMember[]>([{ id: 1, vocation: 'knight', level: 100 }]); const [goal, setGoal] = useState<'exp' | 'profit' | 'balanced'>('exp');
  const [data, setData] = useState<RecommendationResponse | null>(null); const [loading, setLoading] = useState(false); const [loadingMore, setLoadingMore] = useState(false); const [error, setError] = useState(false);
  const [selected, setSelected] = useState<RecommendationItem | null>(null); const [mapBootstrap, setMapBootstrap] = useState<TibiaMapBootstrap | null>(null); const [mapContext, setMapContext] = useState<HuntZoneMapContext | null>(null); const [mapFullscreen, setMapFullscreen] = useState(false);
  const sentinelRef = useRef<HTMLDivElement | null>(null); const initialRef = useRef(false);

  const request = useCallback(async (skip: number) => mode === 'solo'
    ? huntZonesApi.getRecommendations(soloVocation as never, soloLevel, PAGE_SIZE, goal, preferredZone, skip)
    : huntZonesApi.getPartyRecommendations(party.map(({ vocation, level }) => ({ vocation, level: Number(level) })), goal, PAGE_SIZE, skip), [goal, mode, party, preferredZone, soloLevel, soloVocation]);
  const findSpots = useCallback(async () => { setLoading(true); setError(false); setSelected(null); try { setData(await request(0)); } catch { setError(true); setData(null); } finally { setLoading(false); } }, [request]);
  const loadMore = useCallback(async () => { if (!data?.has_more || loadingMore) return; setLoadingMore(true); try { const next = await request(data.recommendations.length); setData({ ...next, recommendations: [...data.recommendations, ...next.recommendations] }); } catch { setError(true); } finally { setLoadingMore(false); } }, [data, loadingMore, request]);
  useEffect(() => { if (!initialRef.current) { initialRef.current = true; void findSpots(); } }, [findSpots]);
  useEffect(() => { const node = sentinelRef.current; if (!node) return undefined; const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) void loadMore(); }, { rootMargin: '300px' }); observer.observe(node); return () => observer.disconnect(); }, [loadMore]);
  useEffect(() => { if (!selected) return undefined; const controller = new AbortController(); const identifier = selected.zone_slug || selected.zone_id; void tibiaMapApi.huntZoneContext(identifier, controller.signal).then((context) => { setMapContext(context); const floor = context.hunt_zone.z ?? selected.location_z ?? 7; return tibiaMapApi.bootstrap(floor, controller.signal); }).then(setMapBootstrap).catch(() => { setMapContext(null); setMapBootstrap(null); }); return () => controller.abort(); }, [selected]);
  const addMember = () => party.length < 4 && setParty([...party, { id: Date.now(), vocation: 'druid', level: 100 }]);
  const formatRate = (value?: number) => value ? `${value.toLocaleString()}/h` : null;

  return <Page className="space-y-6"><PageHeader title={t('plannerRecovery.title')} subtitle={t('plannerRecovery.subtitle')} icon={faCompass} size="md" />
    <div className="grid gap-6 lg:grid-cols-[20rem_minmax(0,1fr)]">
      <div className="space-y-4"><AppTabs activeKey={mode} onChange={(key) => setMode(key as 'solo' | 'party')} items={[{ key: 'solo', label: t('plannerRecovery.solo') }, { key: 'party', label: t('plannerRecovery.party') }]} />
        <AppCard className="space-y-5 p-5"><h2 className="flex items-center gap-2 font-bold">{mode === 'solo' ? <User size={18} /> : <Users size={18} />}{t(mode === 'solo' ? 'plannerRecovery.configuration' : 'plannerRecovery.composition')}</h2>
          {mode === 'solo' ? <><label className="block text-xs font-bold uppercase text-content-muted">{t('plannerRecovery.vocation')}</label><div className="grid grid-cols-5 gap-2">{VOCATIONS.map(({ id, icon: Icon }) => <button key={id} type="button" onClick={() => setSoloVocation(id)} title={t(`plannerRecovery.vocations.${id}`)} aria-label={t(`plannerRecovery.vocations.${id}`)} className={`grid aspect-square place-items-center rounded-xl border ${soloVocation === id ? 'border-primary bg-primary/15 text-primary' : 'border-line'}`}><Icon size={18} /></button>)}</div><label className="block text-xs font-bold uppercase text-content-muted">{t('plannerRecovery.level')}</label><AppInput type="number" min={8} max={2000} value={soloLevel} onChange={(event) => setSoloLevel(Number(event.target.value))} /></> : <div className="space-y-2">{party.map((member, index) => <div key={member.id} className="flex items-center gap-2 rounded-xl border border-line p-2"><span className="text-xs text-content-muted">{index + 1}</span><select value={member.vocation} onChange={(event) => setParty(party.map((row) => row.id === member.id ? { ...row, vocation: event.target.value } : row))} className="app-input flex-1">{VOCATIONS.map(({ id }) => <option key={id} value={id}>{t(`plannerRecovery.vocations.${id}`)}</option>)}</select><input type="number" min={8} max={2000} value={member.level} onChange={(event) => setParty(party.map((row) => row.id === member.id ? { ...row, level: Number(event.target.value) } : row))} aria-label={t('plannerRecovery.level')} className="app-input w-20" /><button type="button" disabled={party.length === 1} onClick={() => setParty(party.filter((row) => row.id !== member.id))} aria-label={t('plannerRecovery.removeMember')}><Trash2 size={15} /></button></div>)}<button type="button" disabled={party.length >= 4} onClick={addMember} className="app-button-secondary app-button-sm w-full"><Plus size={15} />{t('plannerRecovery.addMember')}</button></div>}
          <label className="block text-xs font-bold uppercase text-content-muted">{t('plannerRecovery.goal')}</label><div className="grid grid-cols-3 gap-2">{(['exp', 'profit', 'balanced'] as const).map((item) => <button type="button" key={item} onClick={() => setGoal(item)} className={`rounded-lg border px-2 py-2 text-xs font-bold ${goal === item ? 'border-primary bg-primary/15 text-primary' : 'border-line'}`}>{t(`plannerRecovery.goals.${item}`)}</button>)}</div>
          <AppButton onClick={() => void findSpots()} disabled={loading} className="w-full"><Map size={18} />{loading ? t('plannerRecovery.scouting') : t('plannerRecovery.find')}</AppButton>
        </AppCard>
      </div>
      <section className="space-y-3">{error ? <div role="alert" className="rounded-xl border border-danger/30 bg-danger/10 p-4 text-danger">{t('plannerRecovery.error')}</div> : null}{!loading && !data?.recommendations.length ? <div className="rounded-2xl border border-dashed border-line p-12 text-center text-content-muted">{t('plannerRecovery.empty')}</div> : null}
        {data?.recommendations.map((rec) => <article key={rec.zone_id} className="rounded-2xl border border-line bg-surface-raised p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-serif text-xl font-bold">{rec.zone_name}</h2><p className="mt-1 text-xs text-content-muted">{[rec.city || rec.region, rec.suggested_level ? t('plannerRecovery.levelValue', { level: rec.suggested_level }) : null].filter(Boolean).join(' · ')}</p></div><span className="rounded-lg bg-primary/10 px-2 py-1 text-sm font-bold text-primary">{Math.round(rec.score)}%</span></div>
          <div className="mt-3 flex flex-wrap gap-2">{formatRate(rec.avg_exp_hour) ? <span className="rounded-lg border border-line px-3 py-2 text-sm"><strong>EXP</strong> {formatRate(rec.avg_exp_hour)}</span> : null}{formatRate(rec.avg_profit_hour) ? <span className="rounded-lg border border-line px-3 py-2 text-sm"><strong>Profit</strong> {formatRate(rec.avg_profit_hour)}</span> : null}{rec.raw_creature_exp ? <span className="rounded-lg border border-line px-3 py-2 text-sm"><strong>Raw EXP</strong> {rec.raw_creature_exp.toLocaleString()}</span> : null}</div>
          {rec.creatures?.length ? <div className="mt-3 flex gap-2 overflow-x-auto">{rec.creatures.map((creature) => <button key={creature.id} type="button" onClick={() => setSelected(rec)} title={`${creature.name} · ${creature.hitpoints} HP · ${creature.experience} EXP`} className="flex shrink-0 items-center gap-2 rounded-xl border border-line bg-surface p-2 text-left"><img src={creature.image_url} alt="" className="size-11 object-contain [image-rendering:pixelated]" /><span><strong className="block text-xs">{creature.name}</strong><small className="text-content-muted">{creature.hitpoints} HP · {creature.experience} EXP</small></span></button>)}</div> : null}
          <div className="mt-3 flex justify-end gap-2"><Link to={`/hunt-zones/${rec.zone_slug || rec.zone_id}`} className="app-button-secondary app-button-sm">{t('plannerRecovery.details')}</Link><button type="button" onClick={() => setSelected(rec)} className="app-button-primary app-button-sm"><Map size={15} />{t('plannerRecovery.inspect')}</button></div>
        </article>)}
        <div ref={sentinelRef} className="h-2" aria-hidden="true" />{loadingMore ? <p className="text-center text-sm text-content-muted">{t('plannerRecovery.loadingMore')}</p> : null}
      </section>
    </div>
    {selected ? <div role="dialog" aria-modal="true" aria-label={t('plannerRecovery.inspector')} className="fixed inset-0 z-modal grid place-items-center bg-surface-overlay/90 p-3 backdrop-blur-sm"><div className="flex h-[min(54rem,94dvh)] w-[min(82rem,96vw)] flex-col overflow-hidden rounded-2xl border border-line bg-surface-raised shadow-2xl"><header className="flex items-center justify-between border-b border-line p-3"><h2 className="font-serif text-xl font-bold">{selected.zone_name}</h2><div className="flex gap-2"><button type="button" onClick={() => setMapFullscreen((value) => !value)} aria-label={mapFullscreen ? t('plannerRecovery.reduceMap') : t('plannerRecovery.expandMap')} className="grid size-9 place-items-center rounded-lg border border-line">{mapFullscreen ? <Minimize2 size={16} /> : <Expand size={16} />}</button><button type="button" onClick={() => { setSelected(null); setMapFullscreen(false); }} aria-label={t('plannerRecovery.close')} className="grid size-9 place-items-center rounded-lg border border-line"><X size={16} /></button></div></header>
          <div className={`grid min-h-0 flex-1 ${mapFullscreen ? '' : 'lg:grid-cols-[minmax(0,1.55fr)_minmax(19rem,0.8fr)]'}`}><div className="min-h-[22rem] p-3">{mapBootstrap?.world_map && mapContext ? <Suspense fallback={<div className="h-full bg-surface" />}><TibiaMap imageUrl={mapBootstrap.world_map.image_url} label={selected.zone_name} floor={mapContext.hunt_zone.z} mapBounds={mapBootstrap.world_map.bounds} center={mapContext.hunt_zone.x != null && mapContext.hunt_zone.y != null ? { x: mapContext.hunt_zone.x, y: mapContext.hunt_zone.y } : undefined} markers={mapContext.markers.map((marker) => ({ x: marker.x, y: marker.y, label: marker.name, imageUrl: marker.image_url }))} paths={mapContext.routes.map((route) => ({ id: route.id, label: route.name, points: route.points }))} coordinateMode="world" fill resetLabel={t('map.reset')} zoomInLabel={t('map.zoomIn')} zoomOutLabel={t('map.zoomOut')} emptyMessage={t('map.noBaseMap')} /></Suspense> : <div className="grid h-full place-items-center text-content-muted">{t('map.loading')}</div>}</div>
            {!mapFullscreen ? <aside className="min-h-0 overflow-y-auto border-t border-line p-5 lg:border-l lg:border-t-0"><h3 className="font-bold">{t('plannerRecovery.huntInformation')}</h3><dl className="mt-3 space-y-2 text-sm"><div className="flex justify-between"><dt>{t('plannerRecovery.level')}</dt><dd>{selected.min_level ?? '—'}{selected.max_level ? `–${selected.max_level}` : '+'}</dd></div>{selected.avg_exp_hour ? <div className="flex justify-between"><dt>EXP</dt><dd>{formatRate(selected.avg_exp_hour)}</dd></div> : null}{selected.avg_profit_hour ? <div className="flex justify-between"><dt>Profit</dt><dd>{formatRate(selected.avg_profit_hour)}</dd></div> : null}{selected.raw_creature_exp ? <div className="flex justify-between"><dt>Raw EXP</dt><dd>{selected.raw_creature_exp.toLocaleString()}</dd></div> : null}</dl><h3 className="mt-5 font-bold">{t('plannerRecovery.access')}</h3><p className="mt-2 text-sm text-content-secondary">{[selected.requires_premium ? t('plannerRecovery.premium') : null, selected.requires_quest ? selected.quest_name || t('plannerRecovery.questRequired') : null].filter(Boolean).join(' · ') || t('plannerRecovery.noRestrictions')}</p><h3 className="mt-5 font-bold">{t('plannerRecovery.creatures')}</h3><div className="mt-2 space-y-2">{selected.creatures?.map((creature) => <Link key={creature.id} to={`/creatures/${creature.slug || creature.id}`} className="flex gap-3 rounded-xl border border-line p-2 hover:border-primary/40"><img src={creature.image_url} alt="" className="size-14 object-contain [image-rendering:pixelated]" /><span className="min-w-0 text-xs"><strong className="block text-sm">{creature.name}</strong><span>{creature.hitpoints} HP · {creature.experience} EXP{creature.max_damage ? ` · ${t('plannerRecovery.damage', { value: creature.max_damage })}` : ''}</span>{creature.weaknesses.length ? <span className="block text-success">{t('plannerRecovery.weaknesses')}: {creature.weaknesses.join(', ')}</span> : null}{creature.resistances.length ? <span className="block text-info">{t('plannerRecovery.resistances')}: {creature.resistances.join(', ')}</span> : null}{creature.valuable_loot.length ? <span className="mt-1 block"><Coins className="mr-1 inline size-3" />{creature.valuable_loot.map((loot) => loot.name).join(', ')}</span> : null}</span></Link>)}</div></aside> : null}
          </div></div></div> : null}
  </Page>;
}
