import { lazy, Suspense, useCallback, useEffect, useRef, useState } from 'react';
import { Coins, Expand, Map, Minimize2, Plus, Shield, Sparkles, Swords, Trash2, User, Users, X, Zap, Scroll } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { huntZonesApi } from '../services/api';
import { tibiaMapApi, type HuntZoneMapContext } from '../services/tibiaMap';
import AppButton from '../components/ui/AppButton'; import AppCard from '../components/ui/AppCard'; import AppInput from '../components/ui/AppInput'; import AppTabs from '../components/ui/AppTabs'; import PageHeader from '../components/ui/PageHeader'; import { Page } from '../components/ui';
import { faCompass } from '@fortawesome/free-solid-svg-icons';
import HuntZoneCard from '../components/HuntZoneCard';
import type { HuntZone, HuntZoneSpatial } from '../types';
import { formatDisplayFloor } from '../utils/tibiaFloors';

const TibiaMap = lazy(() => import('../components/map/TibiaMapViewer'));
const VOCATIONS = [{ id: 'knight', icon: Shield }, { id: 'paladin', icon: Swords }, { id: 'sorcerer', icon: Zap }, { id: 'druid', icon: Sparkles }, { id: 'monk', icon: Scroll }];
const PAGE_SIZE = 6;
interface PartyMember { id: number; vocation: string; level: number }
interface CreaturePreview { id: number; name: string; slug?: string; image_url: string; hitpoints: number | null; experience: number | null; max_damage?: number; weaknesses: string[]; resistances: string[]; valuable_loot: Array<{ name: string; value: number; image_url?: string }> }
interface RecommendationItem { zone_id: number; zone_name: string; zone_slug?: string; score: number; min_level?: number | null; max_level?: number | null; suggested_level?: number | null; avg_exp_hour?: number; avg_profit_hour?: number; raw_creature_exp?: number | null; requires_premium?: boolean | null; requires_quest?: boolean | null; quest_name?: string; city?: string; region?: string; size?: string; difficulty?: string; danger?: string; location_z?: number; spatial?: HuntZoneSpatial | null; creatures?: CreaturePreview[] }
interface RecommendationResponse { recommendations: RecommendationItem[]; has_more: boolean; skip: number; limit: number; avg_level?: number; party_size?: number }

export default function HuntRecommendationsPage() {
  const { t } = useTranslation(); const [searchParams] = useSearchParams(); const preferredZone = searchParams.get('zone') || undefined;
  const [mode, setMode] = useState<'solo' | 'party'>('solo'); const [soloVocation, setSoloVocation] = useState('knight'); const [soloLevel, setSoloLevel] = useState(100);
  const [party, setParty] = useState<PartyMember[]>([{ id: 1, vocation: 'knight', level: 100 }]); const [goal, setGoal] = useState<'exp' | 'profit' | 'balanced'>('exp');
  const [data, setData] = useState<RecommendationResponse | null>(null); const [loading, setLoading] = useState(false); const [loadingMore, setLoadingMore] = useState(false); const [error, setError] = useState(false);
  const [selected, setSelected] = useState<RecommendationItem | null>(null); const [mapContext, setMapContext] = useState<HuntZoneMapContext | null>(null); const [mapFullscreen, setMapFullscreen] = useState(false);
  const sentinelRef = useRef<HTMLDivElement | null>(null); const requestRef = useRef<AbortController | null>(null); const mountedRef = useRef(true);

  const request = useCallback(async (skip: number, signal: AbortSignal) => mode === 'solo'
    ? huntZonesApi.getRecommendations(soloVocation as never, soloLevel, PAGE_SIZE, goal, preferredZone, skip, signal)
    : huntZonesApi.getPartyRecommendations(party.map(({ vocation, level }) => ({ vocation, level: Number(level) })), goal, PAGE_SIZE, skip, signal), [goal, mode, party, preferredZone, soloLevel, soloVocation]);
  const findSpots = useCallback(async () => { requestRef.current?.abort(); const controller = new AbortController(); requestRef.current = controller; setLoading(true); setLoadingMore(false); setError(false); setSelected(null); try { const next = await request(0, controller.signal); if (mountedRef.current && !controller.signal.aborted) setData(next); } catch { if (mountedRef.current && !controller.signal.aborted) { setError(true); setData(null); } } finally { if (requestRef.current === controller) { requestRef.current = null; if (mountedRef.current) setLoading(false); } } }, [request]);
  const loadMore = useCallback(async () => { if (!data?.has_more || loading || loadingMore || requestRef.current) return; const controller = new AbortController(); requestRef.current = controller; setLoadingMore(true); try { const next = await request(data.recommendations.length, controller.signal); if (mountedRef.current && !controller.signal.aborted) setData({ ...next, recommendations: [...data.recommendations, ...next.recommendations] }); } catch { if (mountedRef.current && !controller.signal.aborted) setError(true); } finally { if (requestRef.current === controller) { requestRef.current = null; if (mountedRef.current) setLoadingMore(false); } } }, [data, loading, loadingMore, request]);
  useEffect(() => { mountedRef.current = true; void findSpots(); return () => { mountedRef.current = false; requestRef.current?.abort(); }; }, []); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { const node = sentinelRef.current; if (!node) return undefined; const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) void loadMore(); }, { rootMargin: '300px' }); observer.observe(node); return () => observer.disconnect(); }, [loadMore]);
  useEffect(() => { if (!selected || selected.spatial?.geometry_status !== 'mapped') { setMapContext(null); return undefined; } const controller = new AbortController(); let current = true; const identifier = selected.zone_slug || selected.zone_id; setMapContext(tibiaMapApi.peekHuntZoneContext(identifier)); void tibiaMapApi.huntZoneContext(identifier, controller.signal).then((context) => { if (current) setMapContext(context); }).catch(() => { if (current && !controller.signal.aborted) setMapContext(null); }); return () => { current = false; controller.abort(); }; }, [selected]);
  const addMember = () => party.length < 4 && setParty([...party, { id: Date.now(), vocation: 'druid', level: 100 }]);
  const formatRate = (value?: number) => value ? `${value.toLocaleString()}/h` : null;
  const creatureStats = (creature: CreaturePreview) => `${creature.hitpoints ?? t('common.unknown')} HP · ${creature.experience ?? t('common.unknown')} EXP`;
  const accessText = (item: RecommendationItem) => {
    const facts = [item.requires_premium === true ? t('plannerRecovery.premium') : null, item.requires_quest === true ? item.quest_name || t('plannerRecovery.questRequired') : null].filter(Boolean);
    if (facts.length) return facts.join(' · ');
    return item.requires_premium === false && item.requires_quest === false ? t('plannerRecovery.noRestrictions') : t('common.unknown');
  };
  const asZone = (rec: RecommendationItem): HuntZone => ({ id: rec.zone_id, slug: rec.zone_slug, name: rec.zone_name, city: rec.city, region: rec.region, min_level: rec.min_level, max_level: rec.max_level ?? undefined, recommended_level: rec.suggested_level ?? undefined, avg_exp_hour: rec.avg_exp_hour, avg_profit_hour: rec.avg_profit_hour, difficulty: rec.difficulty, danger_rating: rec.danger, requires_premium: rec.requires_premium, requires_quest: rec.requires_quest, spatial: rec.spatial });

  return <Page className="space-y-6"><PageHeader title={t('plannerRecovery.title')} subtitle={t('plannerRecovery.subtitle')} icon={faCompass} size="md" />
    <div className="grid gap-6 lg:grid-cols-[20rem_minmax(0,1fr)]">
      <div className="space-y-4"><AppTabs activeKey={mode} onChange={(key) => setMode(key as 'solo' | 'party')} items={[{ key: 'solo', label: t('plannerRecovery.solo') }, { key: 'party', label: t('plannerRecovery.party') }]} />
        <AppCard className="space-y-5 p-5"><h2 className="flex items-center gap-2 font-bold">{mode === 'solo' ? <User size={18} /> : <Users size={18} />}{t(mode === 'solo' ? 'plannerRecovery.configuration' : 'plannerRecovery.composition')}</h2>
          {mode === 'solo' ? <><label className="block text-xs font-bold uppercase text-content-muted">{t('plannerRecovery.vocation')}</label><div className="grid grid-cols-5 gap-2">{VOCATIONS.map(({ id, icon: Icon }) => <button key={id} type="button" onClick={() => setSoloVocation(id)} title={t(`plannerRecovery.vocations.${id}`)} aria-label={t(`plannerRecovery.vocations.${id}`)} className={`grid aspect-square place-items-center rounded-xl border ${soloVocation === id ? 'border-primary bg-primary/15 text-primary' : 'border-line'}`}><Icon size={18} /></button>)}</div><label className="block text-xs font-bold uppercase text-content-muted">{t('plannerRecovery.level')}</label><AppInput type="number" min={8} max={2000} value={soloLevel} onChange={(event) => setSoloLevel(Number(event.target.value))} /></> : <div className="space-y-2">{party.map((member, index) => <div key={member.id} className="flex items-center gap-2 rounded-xl border border-line p-2"><span className="text-xs text-content-muted">{index + 1}</span><select value={member.vocation} onChange={(event) => setParty(party.map((row) => row.id === member.id ? { ...row, vocation: event.target.value } : row))} className="app-input flex-1">{VOCATIONS.map(({ id }) => <option key={id} value={id}>{t(`plannerRecovery.vocations.${id}`)}</option>)}</select><input type="number" min={8} max={2000} value={member.level} onChange={(event) => setParty(party.map((row) => row.id === member.id ? { ...row, level: Number(event.target.value) } : row))} aria-label={t('plannerRecovery.level')} className="app-input w-20" /><button type="button" disabled={party.length === 1} onClick={() => setParty(party.filter((row) => row.id !== member.id))} aria-label={t('plannerRecovery.removeMember')}><Trash2 size={15} /></button></div>)}<button type="button" disabled={party.length >= 4} onClick={addMember} className="app-button-secondary app-button-sm w-full"><Plus size={15} />{t('plannerRecovery.addMember')}</button></div>}
          <label className="block text-xs font-bold uppercase text-content-muted">{t('plannerRecovery.goal')}</label><div className="grid grid-cols-3 gap-2">{(['exp', 'profit', 'balanced'] as const).map((item) => <button type="button" key={item} onClick={() => setGoal(item)} className={`rounded-lg border px-2 py-2 text-xs font-bold ${goal === item ? 'border-primary bg-primary/15 text-primary' : 'border-line'}`}>{t(`plannerRecovery.goals.${item}`)}</button>)}</div>
          <AppButton onClick={() => void findSpots()} disabled={loading} className="w-full"><Map size={18} />{loading ? t('plannerRecovery.scouting') : t('plannerRecovery.find')}</AppButton>
        </AppCard>
      </div>
      <section className="grid content-start gap-4 sm:grid-cols-2 xl:grid-cols-3">{error ? <div role="alert" className="col-span-full rounded-xl border border-danger/30 bg-danger/10 p-4 text-danger">{t('plannerRecovery.error')}</div> : null}{!loading && !data?.recommendations.length ? <div className="col-span-full rounded-2xl border border-dashed border-line p-12 text-center text-content-muted">{t('plannerRecovery.empty')}</div> : null}
        {data?.recommendations.map((rec) => <HuntZoneCard key={rec.zone_id} zone={asZone(rec)} rawExperience={rec.raw_creature_exp || undefined} score={rec.score} onInspectMap={() => setSelected(rec)} />)}
        <div ref={sentinelRef} className="col-span-full h-2" aria-hidden="true" />{loadingMore ? <p className="col-span-full text-center text-sm text-content-muted">{t('plannerRecovery.loadingMore')}</p> : null}
      </section>
    </div>
    {selected ? <div role="dialog" aria-modal="true" aria-label={t('plannerRecovery.inspector')} className="fixed inset-0 z-modal grid place-items-center bg-surface-overlay/90 p-3 backdrop-blur-sm"><div className="flex h-[min(54rem,94dvh)] w-[min(82rem,96vw)] flex-col overflow-hidden rounded-2xl border border-line bg-surface-raised shadow-2xl"><header className="flex items-center justify-between border-b border-line p-3"><h2 className="font-serif text-xl font-bold">{selected.zone_name}</h2><div className="flex gap-2"><button type="button" onClick={() => setMapFullscreen((value) => !value)} aria-label={mapFullscreen ? t('plannerRecovery.reduceMap') : t('plannerRecovery.expandMap')} className="grid size-9 place-items-center rounded-lg border border-line">{mapFullscreen ? <Minimize2 size={16} /> : <Expand size={16} />}</button><button type="button" onClick={() => { setSelected(null); setMapFullscreen(false); }} aria-label={t('plannerRecovery.close')} className="grid size-9 place-items-center rounded-lg border border-line"><X size={16} /></button></div></header>
          <div className={`grid min-h-0 flex-1 ${mapFullscreen ? '' : 'lg:grid-cols-[minmax(0,1.55fr)_minmax(19rem,0.8fr)]'}`}><div className="min-h-[22rem] p-3">{selected.spatial?.geometry_status === 'mapped' && selected.spatial.world_map && selected.spatial.x != null && selected.spatial.y != null ? <Suspense fallback={<div className="h-full bg-surface" />}><TibiaMap imageUrl={selected.spatial.world_map.image_url} label={selected.zone_name} floor={selected.spatial.z} floorLabel={selected.spatial.z != null ? t('map.floor', { floor: formatDisplayFloor(selected.spatial.z) }) : undefined} mapBounds={selected.spatial.world_map.bounds} center={{ x: selected.spatial.x, y: selected.spatial.y }} markers={(mapContext?.markers || []).map((marker) => ({ x: marker.x, y: marker.y, label: marker.name, imageUrl: marker.image_url }))} paths={(mapContext?.routes || []).map((route) => ({ id: route.id, label: route.name, points: route.points }))} coordinateMode="world" fill resetLabel={t('map.reset')} zoomInLabel={t('map.zoomIn')} zoomOutLabel={t('map.zoomOut')} emptyMessage={t('map.noBaseMap')} /></Suspense> : <div className="grid h-full place-items-center rounded-xl border border-dashed border-line text-content-muted">{t('map.locationNotMapped')}</div>}</div>
            {!mapFullscreen ? <aside className="min-h-0 overflow-y-auto border-t border-line p-5 lg:border-l lg:border-t-0"><h3 className="font-bold">{t('plannerRecovery.huntInformation')}</h3><dl className="mt-3 space-y-2 text-sm"><div className="flex justify-between"><dt>{t('plannerRecovery.level')}</dt><dd>{selected.min_level == null ? t('common.unknown') : `${selected.min_level}${selected.max_level ? `–${selected.max_level}` : '+'}`}</dd></div>{selected.avg_exp_hour ? <div className="flex justify-between"><dt>EXP</dt><dd>{formatRate(selected.avg_exp_hour)}</dd></div> : null}{selected.avg_profit_hour ? <div className="flex justify-between"><dt>Profit</dt><dd>{formatRate(selected.avg_profit_hour)}</dd></div> : null}{selected.raw_creature_exp != null ? <div className="flex justify-between"><dt>Raw EXP</dt><dd>{selected.raw_creature_exp.toLocaleString()}</dd></div> : null}</dl><div className="mt-4 grid grid-cols-2 gap-2"><Link to={`/hunt-zones/${selected.zone_slug || selected.zone_id}`} className="app-button-secondary app-button-sm justify-center">{t('plannerRecovery.details')}</Link><Link to={`/map?q=${encodeURIComponent(selected.zone_name)}&entityType=hunt_zone&slug=${encodeURIComponent(selected.zone_slug || String(selected.zone_id))}&floor=${selected.spatial?.z ?? 7}`} className="app-button-secondary app-button-sm justify-center">{t('plannerPolish.openMap')}</Link></div><h3 className="mt-5 font-bold">{t('plannerRecovery.access')}</h3><p className="mt-2 text-sm text-content-secondary">{accessText(selected)}</p><h3 className="mt-5 font-bold">{t('plannerRecovery.creatures')}</h3><div className="mt-2 space-y-2">{selected.creatures?.map((creature) => <Link key={creature.id} to={`/creatures/${creature.slug || creature.id}`} className="flex gap-3 rounded-xl border border-line p-2 hover:border-primary/40"><img src={creature.image_url} alt="" className="size-14 object-contain [image-rendering:pixelated]" /><span className="min-w-0 text-xs"><strong className="block text-sm">{creature.name}</strong><span>{creatureStats(creature)}{creature.max_damage ? ` · ${t('plannerRecovery.damage', { value: creature.max_damage })}` : ''}</span>{creature.weaknesses.length ? <span className="block text-success">{t('plannerRecovery.weaknesses')}: {creature.weaknesses.join(', ')}</span> : null}{creature.resistances.length ? <span className="block text-info">{t('plannerRecovery.resistances')}: {creature.resistances.join(', ')}</span> : null}{creature.valuable_loot.length ? <span className="mt-1 block"><Coins className="mr-1 inline size-3" />{creature.valuable_loot.map((loot) => loot.name).join(', ')}</span> : null}</span></Link>)}</div></aside> : null}
          </div></div></div> : null}
  </Page>;
}
