import { useState } from 'react';
import { ExternalLink, Link2, Loader2, RefreshCw, Star, Unlink } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { AppButton, Badge, Card, EmptyState } from '../ui';
import { useConfirmation } from '../../context/ConfirmationContext';
import { useToast } from '../../context/ToastContext';
import { CharacterIdentity, OwnershipClaim, ProfileIdentity, profileApi } from '../../services/profile';
import OwnershipClaimDialog from './OwnershipClaimDialog';

export default function CharactersSection({ profile, claims, onProfile, onClaims }: { profile: ProfileIdentity; claims: OwnershipClaim[]; onProfile: (value: ProfileIdentity) => void; onClaims: (value: OwnershipClaim[]) => void }) {
  const { t } = useTranslation(); const toast = useToast(); const confirmation = useConfirmation(); const [busy, setBusy] = useState<number>(); const [claimOpen, setClaimOpen] = useState(false);
  const setPrimary = async (row: CharacterIdentity) => { setBusy(row.id); try { onProfile(await profileApi.setPrimary(row.id)); } catch { toast.error(t('identity.error')); } finally { setBusy(undefined); } };
  const refresh = async (row: CharacterIdentity) => { setBusy(row.id); try { const updated = await profileApi.refreshCharacter(row.id); onProfile({ ...profile, character_details: profile.character_details.map(item => item.id === row.id ? updated : item) }); } catch { toast.error(t('identity.error')); } finally { setBusy(undefined); } };
  const unlink = async (row: CharacterIdentity) => { const ok = await confirmation.confirm(t('identity.unlinkConfirm', { name: row.character_name }), { title: t('identity.unlink'), confirmLabel: t('identity.unlink'), danger: true }); if (!ok) return; setBusy(row.id); try { onProfile(await profileApi.unlinkCharacter(row, t('identity.unlinkReason'))); } catch { toast.error(t('identity.error')); } finally { setBusy(undefined); } };
  return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">{t('identity.characters')}</h2><p className="text-sm text-content-muted">{t('identity.charactersHelp')}</p></div><AppButton onClick={() => setClaimOpen(true)}><Link2 className="size-4" />{t('identity.linkCharacter')}</AppButton></div>
    {profile.character_details.length === 0 ? <EmptyState title={t('identity.noCharacters')} description={t('identity.noCharactersHelp')} action={<AppButton onClick={() => setClaimOpen(true)}>{t('identity.linkCharacter')}</AppButton>} /> : <div className="grid gap-4 lg:grid-cols-2">{profile.character_details.map(row => <Card key={row.id} className="p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="font-semibold">{row.character_name}</h3><p className="text-sm text-content-muted">{row.world_name || '—'} · {row.vocation || '—'} · {t('identity.level')} {row.level ?? '—'}</p></div><div className="flex gap-2">{row.is_primary && <Badge tone="primary"><Star className="size-3" />{t('identity.primary')}</Badge>}<Badge tone={row.ownership_status === 'verified' ? 'success' : 'warning'}>{t(`identity.claim.status.${row.ownership_status}`, { defaultValue: row.ownership_status })}</Badge></div></div><dl className="mt-3 grid grid-cols-2 gap-2 text-sm"><div><dt className="text-content-muted">{t('profile.fields.guild')}</dt><dd>{row.guild_name || '—'}</dd></div><div><dt className="text-content-muted">{t('profile.fields.rank')}</dt><dd>{row.guild_rank || '—'}</dd></div><div><dt className="text-content-muted">{t('identity.verification')}</dt><dd>{row.verification_method || '—'}</dd></div><div><dt className="text-content-muted">{t('identity.roster')}</dt><dd>{t(row.is_current_roster_member ? 'identity.registered' : 'identity.notSynchronized')}</dd></div></dl><div className="mt-4 flex flex-wrap gap-2">{!row.is_primary && <AppButton size="sm" onClick={() => void setPrimary(row)} disabled={busy === row.id}><Star className="size-4" />{t('identity.setPrimary')}</AppButton>}<AppButton size="sm" variant="secondary" onClick={() => void refresh(row)} disabled={busy === row.id}>{busy === row.id ? <Loader2 className="size-4 animate-spin" /> : <RefreshCw className="size-4" />}{t('common.refresh')}</AppButton>{row.guild_name && <Link className="app-button-secondary app-button-sm" to="/guild"><ExternalLink className="size-4" />{t('identity.openGuild')}</Link>}<AppButton size="sm" variant="ghost" onClick={() => void unlink(row)} disabled={busy === row.id}><Unlink className="size-4" />{t('identity.unlink')}</AppButton></div></Card>)}</div>}
    {claims.length > 0 && <button className="text-sm text-primary underline" onClick={() => setClaimOpen(true)}>{t('identity.claim.resume', { count: claims.length })}</button>}
    <OwnershipClaimDialog open={claimOpen} claims={claims} onClose={() => setClaimOpen(false)} onChange={onClaims} />
  </div>;
}
