import { FormEvent, useState } from 'react';
import { LogOut, Mail, Save } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { AppButton, Badge, FormField, Input, Panel } from '../ui';
import { useAuth } from '../../context/AuthContext';
import { useToast } from '../../context/ToastContext';
import { ProfileIdentity, profileApi } from '../../services/profile';
import { isValidPassword } from '../../utils/passwordPolicy';

export default function SecuritySection({ profile, onChange }: { profile: ProfileIdentity; onChange: (value: ProfileIdentity) => void }) {
  const { t, i18n } = useTranslation(); const { logout } = useAuth(); const toast = useToast(); const [busy, setBusy] = useState(false); const [form, setForm] = useState({ current_password: '', new_password: '', confirm: '' });
  const save = async (event: FormEvent) => { event.preventDefault(); if (form.new_password !== form.confirm || !isValidPassword(form.new_password)) { toast.error(t('profile.messages.passwordPolicy')); return; } setBusy(true); try { onChange(await profileApi.update({ current_password: form.current_password, new_password: form.new_password })); setForm({ current_password: '', new_password: '', confirm: '' }); toast.success(t('identity.passwordSaved')); } catch { toast.error(t('identity.error')); } finally { setBusy(false); } };
  const resend = async () => { setBusy(true); try { await profileApi.requestVerification(i18n.language.startsWith('es') ? 'es' : 'en'); toast.success(t('profile.emailVerification.queued')); } catch { toast.error(t('identity.error')); } finally { setBusy(false); } };
  return <div className="space-y-5"><Panel className="p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 font-semibold"><Mail className="size-4" />{t('identity.emailVerification')}</h2><p className="text-sm text-content-muted">{profile.email || '—'}</p></div><div className="flex items-center gap-2"><Badge tone={profile.email_verified_at ? 'success' : 'warning'}>{t(profile.email_verified_at ? 'profile.emailVerification.verified' : 'profile.emailVerification.pending')}</Badge>{!profile.email_verified_at && profile.email && <AppButton size="sm" variant="secondary" disabled={busy} onClick={() => void resend()}>{t('profile.emailVerification.send')}</AppButton>}</div></div></Panel>
    <Panel className="p-5"><h2 className="font-semibold">{t('profile.password.title')}</h2><p className="text-sm text-content-muted">{t('identity.recoveryHelp')}</p><form className="mt-4 grid gap-4 md:grid-cols-3" onSubmit={save}><FormField label={t('profile.password.current')}><Input required type="password" autoComplete="current-password" value={form.current_password} onChange={event => setForm(v => ({ ...v, current_password: event.target.value }))} /></FormField><FormField label={t('profile.password.new')}><Input required type="password" autoComplete="new-password" value={form.new_password} onChange={event => setForm(v => ({ ...v, new_password: event.target.value }))} /></FormField><FormField label={t('profile.password.confirm')}><Input required type="password" autoComplete="new-password" value={form.confirm} onChange={event => setForm(v => ({ ...v, confirm: event.target.value }))} /></FormField><AppButton type="submit" disabled={busy}><Save className="size-4" />{t('common.save')}</AppButton></form></Panel>
    <Panel className="flex flex-wrap items-center justify-between gap-3 p-5"><div><h2 className="font-semibold">{t('identity.activeSession')}</h2><p className="text-sm text-content-muted">{t('identity.logoutHelp')}</p></div><AppButton variant="danger" onClick={logout}><LogOut className="size-4" />{t('accountMenu.logout')}</AppButton></Panel></div>;
}
