import { useEffect, useState } from 'react';
import { Loader2, Save, Shield, PenLine, MessagesSquare } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { guildManagementApi, GuildMember } from '../../services/guildManagement';
import { EmptyState, WorkspaceHeader } from '../../components/workspace/WorkspacePrimitives';
import { useToast } from '../../context/ToastContext';

export default function AdminUsers() {
  const { t } = useTranslation();
  const toast = useToast();
  const [users, setUsers] = useState<GuildMember[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState<number | null>(null);
  const [error, setError] = useState(false);
  const load = () => guildManagementApi.getUsers(0, 500, { include_inactive: true, exclude_test_accounts: false }).then(setUsers).catch(() => setError(true)).finally(() => setLoading(false));
  useEffect(() => { void load(); }, []);
  const update = async (user: GuildMember, patch: Partial<GuildMember>) => { setSaving(user.id); try { const saved = await guildManagementApi.updateUser(user.id, patch); setUsers(items => items.map(item => item.id === saved.id ? saved : item)); toast.success(t('workspace.users.saved', 'Permissions updated')); } catch { toast.error(t('workspace.users.saveFailed', 'Unable to update this user')); } finally { setSaving(null); } };
  return <div className="space-y-4"><WorkspaceHeader title={t('workspace.adminUsers.title', 'Users and roles')} subtitle={t('workspace.adminUsers.subtitle', 'Assign independent platform capabilities without changing guild rank.')} badge={t('workspace.admin.badge')} />{loading ? <div className="flex justify-center p-12"><Loader2 className="h-7 w-7 animate-spin text-[color:var(--color-primary)]" /></div> : error ? <EmptyState title={t('workspace.errors.users', 'Users unavailable')} description={t('workspace.errors.tryAgain')} /> : <div className="grid gap-3">{users.map(user => <article key={user.id} className="admin-panel rounded-xl p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">{user.display_name || user.username}</h2><p className="text-sm text-[color:var(--color-text-muted)]">{user.email || user.username} · {user.guild_name || t('workspace.common.noGuild', 'No guild')}</p></div><span className={`rounded-full px-2 py-1 text-xs ${user.is_active ? 'bg-[color:var(--color-success)]/15 text-[color:var(--color-success)]' : 'bg-[color:var(--color-danger)]/15 text-[color:var(--color-danger)]'}`}>{user.is_active ? t('workspace.users.active', 'Active') : t('workspace.users.inactive', 'Inactive')}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="grid gap-1 text-sm"><span className="text-[color:var(--color-text-muted)]">{t('workspace.users.guildRank', 'Guild rank')}</span><select value={user.guild_rank || 'Unranked'} onChange={event => void update(user, { guild_rank: event.target.value })} className="admin-secondary min-h-11 rounded-lg bg-transparent px-3"><option>Unranked</option><option>Member</option><option>Vice Leader</option><option>Leader</option></select></label>{([['is_superuser', Shield, t('workspace.users.admin', 'Admin')], ['is_moderator', MessagesSquare, t('workspace.users.moderator', 'Moderator')], ['is_writer', PenLine, t('workspace.users.writer', 'Writer')]] as const).map(([key, Icon, label]) => <label key={key} className="admin-secondary flex min-h-11 items-center gap-2 rounded-lg px-3"><input type="checkbox" checked={Boolean(user[key])} disabled={saving === user.id} onChange={event => void update(user, { [key]: event.target.checked })} /><Icon className="h-4 w-4 text-[color:var(--color-primary)]" /><span>{label}</span></label>)}</div>{saving === user.id && <p className="mt-2 flex items-center gap-2 text-xs text-[color:var(--color-text-muted)]"><Save className="h-3 w-3 animate-pulse" />{t('workspace.users.saving', 'Saving…')}</p>}</article>)}</div>}</div>;
}
